/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

module alu_8bit(reset, clock, enable, seld, z, a, b, opc, done);
  wire [7:0] \$0\z[7:0] ;
  wire \$abc$1320$n100 ;
  wire \$abc$1320$n102 ;
  wire \$abc$1320$n103 ;
  wire \$abc$1320$n104 ;
  wire \$abc$1320$n105_1 ;
  wire \$abc$1320$n106_1 ;
  wire \$abc$1320$n107 ;
  wire \$abc$1320$n108_1 ;
  wire \$abc$1320$n109_1 ;
  wire \$abc$1320$n110 ;
  wire \$abc$1320$n111_1 ;
  wire \$abc$1320$n112_1 ;
  wire \$abc$1320$n113 ;
  wire \$abc$1320$n114_1 ;
  wire \$abc$1320$n115_1 ;
  wire \$abc$1320$n116 ;
  wire \$abc$1320$n117 ;
  wire \$abc$1320$n118 ;
  wire \$abc$1320$n119 ;
  wire \$abc$1320$n120_1 ;
  wire \$abc$1320$n121_1 ;
  wire \$abc$1320$n122 ;
  wire \$abc$1320$n123_1 ;
  wire \$abc$1320$n124_1 ;
  wire \$abc$1320$n125 ;
  wire \$abc$1320$n126_1 ;
  wire \$abc$1320$n127_1 ;
  wire \$abc$1320$n128 ;
  wire \$abc$1320$n129_1 ;
  wire \$abc$1320$n130_1 ;
  wire \$abc$1320$n131 ;
  wire \$abc$1320$n132 ;
  wire \$abc$1320$n133 ;
  wire \$abc$1320$n135 ;
  wire \$abc$1320$n136 ;
  wire \$abc$1320$n137 ;
  wire \$abc$1320$n138 ;
  wire \$abc$1320$n139 ;
  wire \$abc$1320$n140 ;
  wire \$abc$1320$n141 ;
  wire \$abc$1320$n142 ;
  wire \$abc$1320$n143 ;
  wire \$abc$1320$n144 ;
  wire \$abc$1320$n145 ;
  wire \$abc$1320$n146 ;
  wire \$abc$1320$n147 ;
  wire \$abc$1320$n148 ;
  wire \$abc$1320$n149 ;
  wire \$abc$1320$n150 ;
  wire \$abc$1320$n151 ;
  wire \$abc$1320$n152 ;
  wire \$abc$1320$n153 ;
  wire \$abc$1320$n154 ;
  wire \$abc$1320$n155 ;
  wire \$abc$1320$n156 ;
  wire \$abc$1320$n157 ;
  wire \$abc$1320$n158 ;
  wire \$abc$1320$n159 ;
  wire \$abc$1320$n160 ;
  wire \$abc$1320$n161 ;
  wire \$abc$1320$n162 ;
  wire \$abc$1320$n163 ;
  wire \$abc$1320$n164 ;
  wire \$abc$1320$n165 ;
  wire \$abc$1320$n166 ;
  wire \$abc$1320$n168 ;
  wire \$abc$1320$n169 ;
  wire \$abc$1320$n170 ;
  wire \$abc$1320$n171 ;
  wire \$abc$1320$n172 ;
  wire \$abc$1320$n173 ;
  wire \$abc$1320$n174 ;
  wire \$abc$1320$n175 ;
  wire \$abc$1320$n176 ;
  wire \$abc$1320$n177 ;
  wire \$abc$1320$n178 ;
  wire \$abc$1320$n179 ;
  wire \$abc$1320$n180 ;
  wire \$abc$1320$n181 ;
  wire \$abc$1320$n182 ;
  wire \$abc$1320$n183 ;
  wire \$abc$1320$n184 ;
  wire \$abc$1320$n185 ;
  wire \$abc$1320$n186 ;
  wire \$abc$1320$n187 ;
  wire \$abc$1320$n188 ;
  wire \$abc$1320$n189 ;
  wire \$abc$1320$n190 ;
  wire \$abc$1320$n191 ;
  wire \$abc$1320$n192 ;
  wire \$abc$1320$n193 ;
  wire \$abc$1320$n194 ;
  wire \$abc$1320$n195 ;
  wire \$abc$1320$n196 ;
  wire \$abc$1320$n197 ;
  wire \$abc$1320$n198 ;
  wire \$abc$1320$n199 ;
  wire \$abc$1320$n200 ;
  wire \$abc$1320$n201 ;
  wire \$abc$1320$n202 ;
  wire \$abc$1320$n203_1 ;
  wire \$abc$1320$n204 ;
  wire \$abc$1320$n205_1 ;
  wire \$abc$1320$n206 ;
  wire \$abc$1320$n207_1 ;
  wire \$abc$1320$n208 ;
  wire \$abc$1320$n209_1 ;
  wire \$abc$1320$n210 ;
  wire \$abc$1320$n211_1 ;
  wire \$abc$1320$n212 ;
  wire \$abc$1320$n213_1 ;
  wire \$abc$1320$n214 ;
  wire \$abc$1320$n215_1 ;
  wire \$abc$1320$n216 ;
  wire \$abc$1320$n217_1 ;
  wire \$abc$1320$n218 ;
  wire \$abc$1320$n219 ;
  wire \$abc$1320$n219_1 ;
  wire \$abc$1320$n220 ;
  wire \$abc$1320$n221 ;
  wire \$abc$1320$n222 ;
  wire \$abc$1320$n223 ;
  wire \$abc$1320$n224 ;
  wire \$abc$1320$n226 ;
  wire \$abc$1320$n227 ;
  wire \$abc$1320$n228 ;
  wire \$abc$1320$n229 ;
  wire \$abc$1320$n230 ;
  wire \$abc$1320$n231 ;
  wire \$abc$1320$n232 ;
  wire \$abc$1320$n233 ;
  wire \$abc$1320$n234 ;
  wire \$abc$1320$n235 ;
  wire \$abc$1320$n236 ;
  wire \$abc$1320$n237 ;
  wire \$abc$1320$n238 ;
  wire \$abc$1320$n239 ;
  wire \$abc$1320$n240 ;
  wire \$abc$1320$n241 ;
  wire \$abc$1320$n242 ;
  wire \$abc$1320$n243 ;
  wire \$abc$1320$n244 ;
  wire \$abc$1320$n245 ;
  wire \$abc$1320$n246 ;
  wire \$abc$1320$n247 ;
  wire \$abc$1320$n248 ;
  wire \$abc$1320$n249 ;
  wire \$abc$1320$n250 ;
  wire \$abc$1320$n251 ;
  wire \$abc$1320$n252 ;
  wire \$abc$1320$n253 ;
  wire \$abc$1320$n254 ;
  wire \$abc$1320$n255 ;
  wire \$abc$1320$n256 ;
  wire \$abc$1320$n257 ;
  wire \$abc$1320$n258 ;
  wire \$abc$1320$n259 ;
  wire \$abc$1320$n260 ;
  wire \$abc$1320$n261 ;
  wire \$abc$1320$n262 ;
  wire \$abc$1320$n263 ;
  wire \$abc$1320$n264 ;
  wire \$abc$1320$n265 ;
  wire \$abc$1320$n266 ;
  wire \$abc$1320$n267 ;
  wire \$abc$1320$n268 ;
  wire \$abc$1320$n269 ;
  wire \$abc$1320$n270 ;
  wire \$abc$1320$n271 ;
  wire \$abc$1320$n272 ;
  wire \$abc$1320$n273 ;
  wire \$abc$1320$n274 ;
  wire \$abc$1320$n275 ;
  wire \$abc$1320$n276 ;
  wire \$abc$1320$n277 ;
  wire \$abc$1320$n278 ;
  wire \$abc$1320$n279 ;
  wire \$abc$1320$n280 ;
  wire \$abc$1320$n281 ;
  wire \$abc$1320$n282 ;
  wire \$abc$1320$n283 ;
  wire \$abc$1320$n284 ;
  wire \$abc$1320$n285 ;
  wire \$abc$1320$n286 ;
  wire \$abc$1320$n287 ;
  wire \$abc$1320$n288 ;
  wire \$abc$1320$n289 ;
  wire \$abc$1320$n290 ;
  wire \$abc$1320$n291 ;
  wire \$abc$1320$n292 ;
  wire \$abc$1320$n293 ;
  wire \$abc$1320$n294 ;
  wire \$abc$1320$n295 ;
  wire \$abc$1320$n296 ;
  wire \$abc$1320$n297 ;
  wire \$abc$1320$n298 ;
  wire \$abc$1320$n299 ;
  wire \$abc$1320$n300 ;
  wire \$abc$1320$n301 ;
  wire \$abc$1320$n302 ;
  wire \$abc$1320$n303 ;
  wire \$abc$1320$n304 ;
  wire \$abc$1320$n305 ;
  wire \$abc$1320$n306 ;
  wire \$abc$1320$n307 ;
  wire \$abc$1320$n308 ;
  wire \$abc$1320$n309 ;
  wire \$abc$1320$n310 ;
  wire \$abc$1320$n311 ;
  wire \$abc$1320$n312 ;
  wire \$abc$1320$n313 ;
  wire \$abc$1320$n314 ;
  wire \$abc$1320$n316 ;
  wire \$abc$1320$n317 ;
  wire \$abc$1320$n318 ;
  wire \$abc$1320$n319 ;
  wire \$abc$1320$n320 ;
  wire \$abc$1320$n321 ;
  wire \$abc$1320$n322 ;
  wire \$abc$1320$n323 ;
  wire \$abc$1320$n324 ;
  wire \$abc$1320$n325 ;
  wire \$abc$1320$n326 ;
  wire \$abc$1320$n327 ;
  wire \$abc$1320$n328 ;
  wire \$abc$1320$n329 ;
  wire \$abc$1320$n330 ;
  wire \$abc$1320$n331 ;
  wire \$abc$1320$n332 ;
  wire \$abc$1320$n333 ;
  wire \$abc$1320$n334 ;
  wire \$abc$1320$n335 ;
  wire \$abc$1320$n336 ;
  wire \$abc$1320$n337 ;
  wire \$abc$1320$n338 ;
  wire \$abc$1320$n339 ;
  wire \$abc$1320$n34 ;
  wire \$abc$1320$n340 ;
  wire \$abc$1320$n341 ;
  wire \$abc$1320$n342 ;
  wire \$abc$1320$n343 ;
  wire \$abc$1320$n344 ;
  wire \$abc$1320$n345 ;
  wire \$abc$1320$n346 ;
  wire \$abc$1320$n347 ;
  wire \$abc$1320$n348 ;
  wire \$abc$1320$n349 ;
  wire \$abc$1320$n35 ;
  wire \$abc$1320$n350 ;
  wire \$abc$1320$n351 ;
  wire \$abc$1320$n352 ;
  wire \$abc$1320$n353 ;
  wire \$abc$1320$n354 ;
  wire \$abc$1320$n355 ;
  wire \$abc$1320$n356 ;
  wire \$abc$1320$n357 ;
  wire \$abc$1320$n358 ;
  wire \$abc$1320$n359 ;
  wire \$abc$1320$n36 ;
  wire \$abc$1320$n360 ;
  wire \$abc$1320$n361 ;
  wire \$abc$1320$n362 ;
  wire \$abc$1320$n363 ;
  wire \$abc$1320$n364 ;
  wire \$abc$1320$n365 ;
  wire \$abc$1320$n366 ;
  wire \$abc$1320$n367 ;
  wire \$abc$1320$n368 ;
  wire \$abc$1320$n369 ;
  wire \$abc$1320$n37 ;
  wire \$abc$1320$n370 ;
  wire \$abc$1320$n371 ;
  wire \$abc$1320$n372 ;
  wire \$abc$1320$n373 ;
  wire \$abc$1320$n374 ;
  wire \$abc$1320$n375 ;
  wire \$abc$1320$n376 ;
  wire \$abc$1320$n377 ;
  wire \$abc$1320$n378 ;
  wire \$abc$1320$n379 ;
  wire \$abc$1320$n38 ;
  wire \$abc$1320$n380 ;
  wire \$abc$1320$n381 ;
  wire \$abc$1320$n382 ;
  wire \$abc$1320$n383 ;
  wire \$abc$1320$n384 ;
  wire \$abc$1320$n385 ;
  wire \$abc$1320$n386 ;
  wire \$abc$1320$n387 ;
  wire \$abc$1320$n388 ;
  wire \$abc$1320$n389 ;
  wire \$abc$1320$n39 ;
  wire \$abc$1320$n390 ;
  wire \$abc$1320$n391 ;
  wire \$abc$1320$n392 ;
  wire \$abc$1320$n393 ;
  wire \$abc$1320$n394 ;
  wire \$abc$1320$n395 ;
  wire \$abc$1320$n396 ;
  wire \$abc$1320$n397 ;
  wire \$abc$1320$n398 ;
  wire \$abc$1320$n399 ;
  wire \$abc$1320$n40 ;
  wire \$abc$1320$n400 ;
  wire \$abc$1320$n401 ;
  wire \$abc$1320$n402 ;
  wire \$abc$1320$n403 ;
  wire \$abc$1320$n404 ;
  wire \$abc$1320$n405 ;
  wire \$abc$1320$n406 ;
  wire \$abc$1320$n407 ;
  wire \$abc$1320$n408 ;
  wire \$abc$1320$n409 ;
  wire \$abc$1320$n41 ;
  wire \$abc$1320$n410 ;
  wire \$abc$1320$n411 ;
  wire \$abc$1320$n412 ;
  wire \$abc$1320$n413 ;
  wire \$abc$1320$n414 ;
  wire \$abc$1320$n416 ;
  wire \$abc$1320$n417 ;
  wire \$abc$1320$n418 ;
  wire \$abc$1320$n419 ;
  wire \$abc$1320$n42 ;
  wire \$abc$1320$n420 ;
  wire \$abc$1320$n421 ;
  wire \$abc$1320$n422 ;
  wire \$abc$1320$n423 ;
  wire \$abc$1320$n424 ;
  wire \$abc$1320$n425 ;
  wire \$abc$1320$n426 ;
  wire \$abc$1320$n427 ;
  wire \$abc$1320$n428 ;
  wire \$abc$1320$n429 ;
  wire \$abc$1320$n43 ;
  wire \$abc$1320$n430 ;
  wire \$abc$1320$n431 ;
  wire \$abc$1320$n432 ;
  wire \$abc$1320$n433 ;
  wire \$abc$1320$n434 ;
  wire \$abc$1320$n435 ;
  wire \$abc$1320$n436 ;
  wire \$abc$1320$n437 ;
  wire \$abc$1320$n438 ;
  wire \$abc$1320$n439 ;
  wire \$abc$1320$n44 ;
  wire \$abc$1320$n440 ;
  wire \$abc$1320$n441 ;
  wire \$abc$1320$n442 ;
  wire \$abc$1320$n443 ;
  wire \$abc$1320$n444 ;
  wire \$abc$1320$n445 ;
  wire \$abc$1320$n446 ;
  wire \$abc$1320$n447 ;
  wire \$abc$1320$n448 ;
  wire \$abc$1320$n449 ;
  wire \$abc$1320$n45 ;
  wire \$abc$1320$n450 ;
  wire \$abc$1320$n451 ;
  wire \$abc$1320$n452 ;
  wire \$abc$1320$n453 ;
  wire \$abc$1320$n454 ;
  wire \$abc$1320$n455 ;
  wire \$abc$1320$n456 ;
  wire \$abc$1320$n457 ;
  wire \$abc$1320$n458 ;
  wire \$abc$1320$n459 ;
  wire \$abc$1320$n46 ;
  wire \$abc$1320$n460 ;
  wire \$abc$1320$n461 ;
  wire \$abc$1320$n462 ;
  wire \$abc$1320$n463 ;
  wire \$abc$1320$n464 ;
  wire \$abc$1320$n465 ;
  wire \$abc$1320$n466 ;
  wire \$abc$1320$n467 ;
  wire \$abc$1320$n468 ;
  wire \$abc$1320$n469 ;
  wire \$abc$1320$n47 ;
  wire \$abc$1320$n470 ;
  wire \$abc$1320$n471 ;
  wire \$abc$1320$n472 ;
  wire \$abc$1320$n473 ;
  wire \$abc$1320$n474 ;
  wire \$abc$1320$n475 ;
  wire \$abc$1320$n476 ;
  wire \$abc$1320$n477 ;
  wire \$abc$1320$n478 ;
  wire \$abc$1320$n479 ;
  wire \$abc$1320$n48 ;
  wire \$abc$1320$n480 ;
  wire \$abc$1320$n481 ;
  wire \$abc$1320$n482 ;
  wire \$abc$1320$n483 ;
  wire \$abc$1320$n484 ;
  wire \$abc$1320$n485 ;
  wire \$abc$1320$n486 ;
  wire \$abc$1320$n487 ;
  wire \$abc$1320$n488 ;
  wire \$abc$1320$n489 ;
  wire \$abc$1320$n49 ;
  wire \$abc$1320$n490 ;
  wire \$abc$1320$n491 ;
  wire \$abc$1320$n492 ;
  wire \$abc$1320$n493 ;
  wire \$abc$1320$n494 ;
  wire \$abc$1320$n495 ;
  wire \$abc$1320$n496 ;
  wire \$abc$1320$n497 ;
  wire \$abc$1320$n498 ;
  wire \$abc$1320$n499 ;
  wire \$abc$1320$n50 ;
  wire \$abc$1320$n500 ;
  wire \$abc$1320$n501 ;
  wire \$abc$1320$n502 ;
  wire \$abc$1320$n503 ;
  wire \$abc$1320$n504 ;
  wire \$abc$1320$n505 ;
  wire \$abc$1320$n506 ;
  wire \$abc$1320$n507 ;
  wire \$abc$1320$n508 ;
  wire \$abc$1320$n509 ;
  wire \$abc$1320$n51 ;
  wire \$abc$1320$n510 ;
  wire \$abc$1320$n511 ;
  wire \$abc$1320$n512 ;
  wire \$abc$1320$n513 ;
  wire \$abc$1320$n514 ;
  wire \$abc$1320$n515 ;
  wire \$abc$1320$n516 ;
  wire \$abc$1320$n517 ;
  wire \$abc$1320$n518 ;
  wire \$abc$1320$n519 ;
  wire \$abc$1320$n52 ;
  wire \$abc$1320$n520 ;
  wire \$abc$1320$n521 ;
  wire \$abc$1320$n522 ;
  wire \$abc$1320$n523 ;
  wire \$abc$1320$n524 ;
  wire \$abc$1320$n525 ;
  wire \$abc$1320$n526 ;
  wire \$abc$1320$n527 ;
  wire \$abc$1320$n528 ;
  wire \$abc$1320$n529 ;
  wire \$abc$1320$n53 ;
  wire \$abc$1320$n530 ;
  wire \$abc$1320$n531 ;
  wire \$abc$1320$n532 ;
  wire \$abc$1320$n533 ;
  wire \$abc$1320$n534 ;
  wire \$abc$1320$n535 ;
  wire \$abc$1320$n536 ;
  wire \$abc$1320$n537 ;
  wire \$abc$1320$n538 ;
  wire \$abc$1320$n539 ;
  wire \$abc$1320$n54 ;
  wire \$abc$1320$n541 ;
  wire \$abc$1320$n542 ;
  wire \$abc$1320$n543 ;
  wire \$abc$1320$n544 ;
  wire \$abc$1320$n545 ;
  wire \$abc$1320$n546 ;
  wire \$abc$1320$n547 ;
  wire \$abc$1320$n548 ;
  wire \$abc$1320$n549 ;
  wire \$abc$1320$n55 ;
  wire \$abc$1320$n550 ;
  wire \$abc$1320$n551 ;
  wire \$abc$1320$n552 ;
  wire \$abc$1320$n553 ;
  wire \$abc$1320$n554 ;
  wire \$abc$1320$n555 ;
  wire \$abc$1320$n556 ;
  wire \$abc$1320$n557 ;
  wire \$abc$1320$n558 ;
  wire \$abc$1320$n559 ;
  wire \$abc$1320$n56 ;
  wire \$abc$1320$n560 ;
  wire \$abc$1320$n561 ;
  wire \$abc$1320$n562 ;
  wire \$abc$1320$n563 ;
  wire \$abc$1320$n564 ;
  wire \$abc$1320$n565 ;
  wire \$abc$1320$n566 ;
  wire \$abc$1320$n567 ;
  wire \$abc$1320$n568 ;
  wire \$abc$1320$n569 ;
  wire \$abc$1320$n57 ;
  wire \$abc$1320$n570 ;
  wire \$abc$1320$n571 ;
  wire \$abc$1320$n572 ;
  wire \$abc$1320$n573 ;
  wire \$abc$1320$n574 ;
  wire \$abc$1320$n575 ;
  wire \$abc$1320$n576 ;
  wire \$abc$1320$n577 ;
  wire \$abc$1320$n578 ;
  wire \$abc$1320$n579 ;
  wire \$abc$1320$n58 ;
  wire \$abc$1320$n580 ;
  wire \$abc$1320$n581 ;
  wire \$abc$1320$n582 ;
  wire \$abc$1320$n583 ;
  wire \$abc$1320$n584 ;
  wire \$abc$1320$n585 ;
  wire \$abc$1320$n586 ;
  wire \$abc$1320$n587 ;
  wire \$abc$1320$n588 ;
  wire \$abc$1320$n589 ;
  wire \$abc$1320$n59 ;
  wire \$abc$1320$n590 ;
  wire \$abc$1320$n591 ;
  wire \$abc$1320$n592 ;
  wire \$abc$1320$n593 ;
  wire \$abc$1320$n594 ;
  wire \$abc$1320$n595 ;
  wire \$abc$1320$n596 ;
  wire \$abc$1320$n597 ;
  wire \$abc$1320$n598 ;
  wire \$abc$1320$n599 ;
  wire \$abc$1320$n60 ;
  wire \$abc$1320$n600 ;
  wire \$abc$1320$n601 ;
  wire \$abc$1320$n602 ;
  wire \$abc$1320$n603 ;
  wire \$abc$1320$n604 ;
  wire \$abc$1320$n605 ;
  wire \$abc$1320$n606 ;
  wire \$abc$1320$n607 ;
  wire \$abc$1320$n608 ;
  wire \$abc$1320$n609 ;
  wire \$abc$1320$n61 ;
  wire \$abc$1320$n610 ;
  wire \$abc$1320$n611 ;
  wire \$abc$1320$n612 ;
  wire \$abc$1320$n613 ;
  wire \$abc$1320$n614 ;
  wire \$abc$1320$n615 ;
  wire \$abc$1320$n616 ;
  wire \$abc$1320$n617 ;
  wire \$abc$1320$n618 ;
  wire \$abc$1320$n619 ;
  wire \$abc$1320$n62 ;
  wire \$abc$1320$n620 ;
  wire \$abc$1320$n621 ;
  wire \$abc$1320$n622 ;
  wire \$abc$1320$n623 ;
  wire \$abc$1320$n624 ;
  wire \$abc$1320$n625 ;
  wire \$abc$1320$n626 ;
  wire \$abc$1320$n627 ;
  wire \$abc$1320$n628 ;
  wire \$abc$1320$n629 ;
  wire \$abc$1320$n63 ;
  wire \$abc$1320$n631 ;
  wire \$abc$1320$n64 ;
  wire \$abc$1320$n65 ;
  wire \$abc$1320$n66 ;
  wire \$abc$1320$n67 ;
  wire \$abc$1320$n68 ;
  wire \$abc$1320$n69 ;
  wire \$abc$1320$n70 ;
  wire \$abc$1320$n71 ;
  wire \$abc$1320$n72 ;
  wire \$abc$1320$n73 ;
  wire \$abc$1320$n74 ;
  wire \$abc$1320$n75 ;
  wire \$abc$1320$n76 ;
  wire \$abc$1320$n77 ;
  wire \$abc$1320$n78 ;
  wire \$abc$1320$n79 ;
  wire \$abc$1320$n80 ;
  wire \$abc$1320$n81 ;
  wire \$abc$1320$n82 ;
  wire \$abc$1320$n83 ;
  wire \$abc$1320$n84 ;
  wire \$abc$1320$n85 ;
  wire \$abc$1320$n86 ;
  wire \$abc$1320$n87 ;
  wire \$abc$1320$n88 ;
  wire \$abc$1320$n89 ;
  wire \$abc$1320$n90 ;
  wire \$abc$1320$n91 ;
  wire \$abc$1320$n92 ;
  wire \$abc$1320$n93 ;
  wire \$abc$1320$n94 ;
  wire \$abc$1320$n95 ;
  wire \$abc$1320$n96 ;
  wire \$abc$1320$n97 ;
  wire \$abc$1320$n98 ;
  wire \$abc$1320$n99 ;
  input [7:0] a;
  input [7:0] b;
  input clock;
  output done;
  input enable;
  input [7:0] opc;
  input reset;
  input [1:0] seld;
  output [7:0] z;
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1321  (
    .A(b[0]),
    .B(a[0]),
    .Y(\$abc$1320$n34 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1322  (
    .A(a[0]),
    .Y(\$abc$1320$n35 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1323  (
    .A(b[0]),
    .Y(\$abc$1320$n36 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1324  (
    .A(\$abc$1320$n36 ),
    .B(\$abc$1320$n35 ),
    .Y(\$abc$1320$n37 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1325  (
    .A(\$abc$1320$n37 ),
    .B(\$abc$1320$n34 ),
    .Y(\$abc$1320$n38 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1326  (
    .A(opc[0]),
    .Y(\$abc$1320$n39 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1327  (
    .A(opc[1]),
    .Y(\$abc$1320$n40 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1328  (
    .A(opc[7]),
    .B(opc[6]),
    .Y(\$abc$1320$n41 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1329  (
    .A(opc[5]),
    .B(opc[4]),
    .Y(\$abc$1320$n42 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1330  (
    .A(\$abc$1320$n42 ),
    .B(\$abc$1320$n41 ),
    .Y(\$abc$1320$n43 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1331  (
    .A(\$abc$1320$n43 ),
    .B(opc[3]),
    .Y(\$abc$1320$n44 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1332  (
    .A(\$abc$1320$n44 ),
    .Y(\$abc$1320$n45 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1333  (
    .A(\$abc$1320$n45 ),
    .B(\$abc$1320$n40 ),
    .Y(\$abc$1320$n46 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1334  (
    .A(\$abc$1320$n46 ),
    .Y(\$abc$1320$n47 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1335  (
    .A(\$abc$1320$n47 ),
    .B(opc[2]),
    .Y(\$abc$1320$n48 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1336  (
    .A(\$abc$1320$n48 ),
    .Y(\$abc$1320$n49 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1337  (
    .A(\$abc$1320$n49 ),
    .B(\$abc$1320$n39 ),
    .Y(\$abc$1320$n50 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1338  (
    .A(\$abc$1320$n50 ),
    .Y(\$abc$1320$n51 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1339  (
    .A(\$abc$1320$n44 ),
    .B(opc[2]),
    .Y(\$abc$1320$n52 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1340  (
    .A(\$abc$1320$n52 ),
    .Y(\$abc$1320$n53 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1341  (
    .A(\$abc$1320$n53 ),
    .B(\$abc$1320$n46 ),
    .Y(\$abc$1320$n54 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1342  (
    .A(\$abc$1320$n54 ),
    .Y(\$abc$1320$n55 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1343  (
    .A(\$abc$1320$n55 ),
    .B(\$abc$1320$n51 ),
    .Y(\$abc$1320$n56 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1344  (
    .A(\$abc$1320$n56 ),
    .B(\$abc$1320$n38 ),
    .Y(\$abc$1320$n57 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1345  (
    .A(b[5]),
    .Y(\$abc$1320$n58 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1346  (
    .A(b[6]),
    .Y(\$abc$1320$n59 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1347  (
    .A(\$abc$1320$n59 ),
    .B(\$abc$1320$n58 ),
    .Y(\$abc$1320$n60 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1348  (
    .A(b[4]),
    .Y(\$abc$1320$n61 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1349  (
    .A(b[7]),
    .Y(\$abc$1320$n62 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1350  (
    .A(\$abc$1320$n62 ),
    .B(\$abc$1320$n61 ),
    .Y(\$abc$1320$n63 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1351  (
    .A(\$abc$1320$n63 ),
    .B(\$abc$1320$n60 ),
    .Y(\$abc$1320$n64 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1352  (
    .A(b[1]),
    .Y(\$abc$1320$n65 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1353  (
    .A(\$abc$1320$n65 ),
    .B(\$abc$1320$n36 ),
    .Y(\$abc$1320$n66 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1354  (
    .A(b[2]),
    .Y(\$abc$1320$n67 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1355  (
    .A(b[3]),
    .Y(\$abc$1320$n68 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1356  (
    .A(\$abc$1320$n68 ),
    .B(\$abc$1320$n67 ),
    .Y(\$abc$1320$n69 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1357  (
    .A(\$abc$1320$n69 ),
    .B(\$abc$1320$n66 ),
    .Y(\$abc$1320$n70 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1358  (
    .A(\$abc$1320$n70 ),
    .B(\$abc$1320$n64 ),
    .Y(\$abc$1320$n71 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1359  (
    .A(\$abc$1320$n71 ),
    .B(opc[0]),
    .Y(\$abc$1320$n72 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1360  (
    .A(a[4]),
    .Y(\$abc$1320$n73 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1361  (
    .A(a[5]),
    .Y(\$abc$1320$n74 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1362  (
    .A(\$abc$1320$n74 ),
    .B(\$abc$1320$n73 ),
    .Y(\$abc$1320$n75 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1363  (
    .A(a[6]),
    .Y(\$abc$1320$n76 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1364  (
    .A(a[7]),
    .Y(\$abc$1320$n77 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1365  (
    .A(\$abc$1320$n77 ),
    .B(\$abc$1320$n76 ),
    .Y(\$abc$1320$n78 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1366  (
    .A(\$abc$1320$n78 ),
    .B(\$abc$1320$n75 ),
    .Y(\$abc$1320$n79 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1367  (
    .A(a[3]),
    .B(a[1]),
    .Y(\$abc$1320$n80 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1368  (
    .A(\$abc$1320$n80 ),
    .Y(\$abc$1320$n81 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1369  (
    .A(a[2]),
    .B(a[0]),
    .Y(\$abc$1320$n82 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1370  (
    .A(\$abc$1320$n82 ),
    .Y(\$abc$1320$n83 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1371  (
    .A(\$abc$1320$n83 ),
    .B(\$abc$1320$n81 ),
    .Y(\$abc$1320$n84 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1372  (
    .A(\$abc$1320$n84 ),
    .B(\$abc$1320$n79 ),
    .Y(\$abc$1320$n85 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1373  (
    .A(\$abc$1320$n85 ),
    .B(opc[1]),
    .Y(\$abc$1320$n86 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1374  (
    .A(\$abc$1320$n86 ),
    .B(\$abc$1320$n72 ),
    .Y(\$abc$1320$n87 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1375  (
    .A(\$abc$1320$n37 ),
    .Y(\$abc$1320$n88 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1376  (
    .A(\$abc$1320$n88 ),
    .B(\$abc$1320$n39 ),
    .Y(\$abc$1320$n89 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1377  (
    .A(\$abc$1320$n34 ),
    .B(opc[1]),
    .Y(\$abc$1320$n90 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1378  (
    .A(\$abc$1320$n90 ),
    .B(\$abc$1320$n89 ),
    .Y(\$abc$1320$n91 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1379  (
    .A(\$abc$1320$n40 ),
    .B(\$abc$1320$n39 ),
    .Y(\$abc$1320$n92 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1380  (
    .A(\$abc$1320$n92 ),
    .B(\$abc$1320$n71 ),
    .Y(\$abc$1320$n93 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1381  (
    .A(\$abc$1320$n93 ),
    .B(\$abc$1320$n91 ),
    .Y(\$abc$1320$n94 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1382  (
    .A(\$abc$1320$n94 ),
    .B(\$abc$1320$n87 ),
    .Y(\$abc$1320$n95 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1383  (
    .A(\$abc$1320$n95 ),
    .B(\$abc$1320$n52 ),
    .Y(\$abc$1320$n96 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1384  (
    .A(\$abc$1320$n49 ),
    .B(opc[0]),
    .Y(\$abc$1320$n97 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1385  (
    .A(\$abc$1320$n97 ),
    .Y(\$abc$1320$n98 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1386  (
    .A(\$abc$1320$n98 ),
    .B(\$abc$1320$n88 ),
    .Y(\$abc$1320$n99 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1387  (
    .A(\$abc$1320$n99 ),
    .B(\$abc$1320$n96 ),
    .Y(\$abc$1320$n100 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1388  (
    .A(\$abc$1320$n100 ),
    .B(\$abc$1320$n57 ),
    .Y(\$0\z[7:0] [0])
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1389  (
    .A(b[1]),
    .B(a[1]),
    .Y(\$abc$1320$n102 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1390  (
    .A(\$abc$1320$n102 ),
    .Y(\$abc$1320$n103 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1391  (
    .A(b[1]),
    .B(a[1]),
    .Y(\$abc$1320$n104 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1392  (
    .A(\$abc$1320$n104 ),
    .B(\$abc$1320$n103 ),
    .Y(\$abc$1320$n105_1 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1393  (
    .A(\$abc$1320$n105_1 ),
    .Y(\$abc$1320$n106_1 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1394  (
    .A(\$abc$1320$n106_1 ),
    .B(\$abc$1320$n51 ),
    .Y(\$abc$1320$n107 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1395  (
    .A(a[1]),
    .Y(\$abc$1320$n108_1 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1396  (
    .A(\$abc$1320$n36 ),
    .B(\$abc$1320$n108_1 ),
    .Y(\$abc$1320$n109_1 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1397  (
    .A(\$abc$1320$n65 ),
    .B(\$abc$1320$n35 ),
    .Y(\$abc$1320$n110 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1398  (
    .A(\$abc$1320$n110 ),
    .B(\$abc$1320$n109_1 ),
    .Y(\$abc$1320$n111_1 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1399  (
    .A(b[0]),
    .B(a[1]),
    .Y(\$abc$1320$n112_1 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1400  (
    .A(\$abc$1320$n110 ),
    .Y(\$abc$1320$n113 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1401  (
    .A(\$abc$1320$n113 ),
    .B(\$abc$1320$n112_1 ),
    .Y(\$abc$1320$n114_1 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1402  (
    .A(\$abc$1320$n114_1 ),
    .B(\$abc$1320$n111_1 ),
    .Y(\$abc$1320$n115_1 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1403  (
    .A(\$abc$1320$n115_1 ),
    .B(\$abc$1320$n98 ),
    .Y(\$abc$1320$n116 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1404  (
    .A(\$abc$1320$n116 ),
    .B(\$abc$1320$n107 ),
    .Y(\$abc$1320$n117 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1405  (
    .A(\$abc$1320$n36 ),
    .B(a[0]),
    .Y(\$abc$1320$n118 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1406  (
    .A(\$abc$1320$n118 ),
    .B(\$abc$1320$n105_1 ),
    .Y(\$abc$1320$n119 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1407  (
    .A(\$abc$1320$n118 ),
    .B(\$abc$1320$n105_1 ),
    .Y(\$abc$1320$n120_1 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1408  (
    .A(\$abc$1320$n120_1 ),
    .B(\$abc$1320$n54 ),
    .Y(\$abc$1320$n121_1 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1409  (
    .A(\$abc$1320$n121_1 ),
    .B(\$abc$1320$n119 ),
    .Y(\$abc$1320$n122 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1410  (
    .A(opc[1]),
    .B(opc[0]),
    .Y(\$abc$1320$n123_1 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1411  (
    .A(\$abc$1320$n123_1 ),
    .Y(\$abc$1320$n124_1 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1412  (
    .A(\$abc$1320$n124_1 ),
    .B(\$abc$1320$n52 ),
    .Y(\$abc$1320$n125 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1413  (
    .A(\$abc$1320$n125 ),
    .B(\$abc$1320$n103 ),
    .Y(\$abc$1320$n126_1 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1414  (
    .A(\$abc$1320$n104 ),
    .Y(\$abc$1320$n127_1 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1415  (
    .A(opc[1]),
    .B(\$abc$1320$n39 ),
    .Y(\$abc$1320$n128 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1416  (
    .A(\$abc$1320$n128 ),
    .B(\$abc$1320$n53 ),
    .Y(\$abc$1320$n129_1 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1417  (
    .A(\$abc$1320$n129_1 ),
    .Y(\$abc$1320$n130_1 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1418  (
    .A(\$abc$1320$n130_1 ),
    .B(\$abc$1320$n127_1 ),
    .Y(\$abc$1320$n131 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1419  (
    .A(\$abc$1320$n131 ),
    .B(\$abc$1320$n126_1 ),
    .Y(\$abc$1320$n132 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1420  (
    .A(\$abc$1320$n132 ),
    .B(\$abc$1320$n122 ),
    .Y(\$abc$1320$n133 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1421  (
    .A(\$abc$1320$n133 ),
    .B(\$abc$1320$n117 ),
    .Y(\$0\z[7:0] [1])
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1422  (
    .A(b[2]),
    .B(a[2]),
    .Y(\$abc$1320$n135 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1423  (
    .A(\$abc$1320$n135 ),
    .B(\$abc$1320$n129_1 ),
    .Y(\$abc$1320$n136 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1424  (
    .A(a[2]),
    .Y(\$abc$1320$n137 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1425  (
    .A(\$abc$1320$n67 ),
    .B(\$abc$1320$n137 ),
    .Y(\$abc$1320$n138 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1426  (
    .A(\$abc$1320$n138 ),
    .B(\$abc$1320$n125 ),
    .Y(\$abc$1320$n139 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1427  (
    .A(\$abc$1320$n138 ),
    .B(\$abc$1320$n135 ),
    .Y(\$abc$1320$n140 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1428  (
    .A(\$abc$1320$n140 ),
    .Y(\$abc$1320$n141 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1429  (
    .A(\$abc$1320$n141 ),
    .B(\$abc$1320$n51 ),
    .Y(\$abc$1320$n142 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1430  (
    .A(\$abc$1320$n67 ),
    .B(\$abc$1320$n35 ),
    .Y(\$abc$1320$n143 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1431  (
    .A(\$abc$1320$n143 ),
    .Y(\$abc$1320$n144 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1432  (
    .A(b[0]),
    .B(a[2]),
    .Y(\$abc$1320$n145 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1433  (
    .A(\$abc$1320$n145 ),
    .B(\$abc$1320$n102 ),
    .Y(\$abc$1320$n146 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1434  (
    .A(\$abc$1320$n112_1 ),
    .B(\$abc$1320$n82 ),
    .Y(\$abc$1320$n147 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1435  (
    .A(\$abc$1320$n137 ),
    .B(\$abc$1320$n35 ),
    .Y(\$abc$1320$n148 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1436  (
    .A(\$abc$1320$n148 ),
    .B(\$abc$1320$n65 ),
    .Y(\$abc$1320$n149 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1437  (
    .A(\$abc$1320$n149 ),
    .B(\$abc$1320$n147 ),
    .Y(\$abc$1320$n150 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1438  (
    .A(\$abc$1320$n150 ),
    .B(\$abc$1320$n146 ),
    .Y(\$abc$1320$n151 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1439  (
    .A(\$abc$1320$n151 ),
    .Y(\$abc$1320$n152 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1440  (
    .A(\$abc$1320$n152 ),
    .B(\$abc$1320$n144 ),
    .Y(\$abc$1320$n153 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1441  (
    .A(\$abc$1320$n151 ),
    .B(\$abc$1320$n143 ),
    .Y(\$abc$1320$n154 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1442  (
    .A(\$abc$1320$n154 ),
    .B(\$abc$1320$n153 ),
    .Y(\$abc$1320$n155 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1443  (
    .A(\$abc$1320$n155 ),
    .B(\$abc$1320$n98 ),
    .Y(\$abc$1320$n156 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1444  (
    .A(\$abc$1320$n156 ),
    .B(\$abc$1320$n142 ),
    .Y(\$abc$1320$n157 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1445  (
    .A(\$abc$1320$n157 ),
    .B(\$abc$1320$n139 ),
    .Y(\$abc$1320$n158 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1446  (
    .A(\$abc$1320$n158 ),
    .B(\$abc$1320$n136 ),
    .Y(\$abc$1320$n159 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1447  (
    .A(b[1]),
    .B(\$abc$1320$n108_1 ),
    .Y(\$abc$1320$n160 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1448  (
    .A(\$abc$1320$n160 ),
    .B(\$abc$1320$n119 ),
    .Y(\$abc$1320$n161 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1449  (
    .A(\$abc$1320$n161 ),
    .B(\$abc$1320$n140 ),
    .Y(\$abc$1320$n162 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1450  (
    .A(\$abc$1320$n161 ),
    .Y(\$abc$1320$n163 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1451  (
    .A(\$abc$1320$n163 ),
    .B(\$abc$1320$n141 ),
    .Y(\$abc$1320$n164 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1452  (
    .A(\$abc$1320$n164 ),
    .B(\$abc$1320$n162 ),
    .Y(\$abc$1320$n165 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1453  (
    .A(\$abc$1320$n165 ),
    .B(\$abc$1320$n54 ),
    .Y(\$abc$1320$n166 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1454  (
    .A(\$abc$1320$n166 ),
    .B(\$abc$1320$n159 ),
    .Y(\$0\z[7:0] [2])
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1455  (
    .A(b[3]),
    .B(a[3]),
    .Y(\$abc$1320$n168 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1456  (
    .A(a[3]),
    .Y(\$abc$1320$n169 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1457  (
    .A(\$abc$1320$n68 ),
    .B(\$abc$1320$n169 ),
    .Y(\$abc$1320$n170 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1458  (
    .A(\$abc$1320$n170 ),
    .B(\$abc$1320$n168 ),
    .Y(\$abc$1320$n171 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1459  (
    .A(\$abc$1320$n171 ),
    .Y(\$abc$1320$n172 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1460  (
    .A(b[2]),
    .B(\$abc$1320$n137 ),
    .Y(\$abc$1320$n173 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1461  (
    .A(\$abc$1320$n173 ),
    .B(\$abc$1320$n162 ),
    .Y(\$abc$1320$n174 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1462  (
    .A(\$abc$1320$n174 ),
    .Y(\$abc$1320$n175 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1463  (
    .A(\$abc$1320$n175 ),
    .B(\$abc$1320$n172 ),
    .Y(\$abc$1320$n176 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1464  (
    .A(\$abc$1320$n174 ),
    .B(\$abc$1320$n171 ),
    .Y(\$abc$1320$n177 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1465  (
    .A(\$abc$1320$n177 ),
    .B(\$abc$1320$n176 ),
    .Y(\$abc$1320$n178 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1466  (
    .A(\$abc$1320$n178 ),
    .B(\$abc$1320$n55 ),
    .Y(\$abc$1320$n179 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1467  (
    .A(\$abc$1320$n68 ),
    .B(\$abc$1320$n35 ),
    .Y(\$abc$1320$n180 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1468  (
    .A(\$abc$1320$n151 ),
    .B(\$abc$1320$n35 ),
    .Y(\$abc$1320$n181 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1469  (
    .A(\$abc$1320$n181 ),
    .Y(\$abc$1320$n182 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1470  (
    .A(b[0]),
    .B(a[3]),
    .Y(\$abc$1320$n183 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1471  (
    .A(\$abc$1320$n183 ),
    .Y(\$abc$1320$n184 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1472  (
    .A(\$abc$1320$n147 ),
    .B(a[2]),
    .Y(\$abc$1320$n185 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1473  (
    .A(\$abc$1320$n36 ),
    .B(\$abc$1320$n137 ),
    .Y(\$abc$1320$n186 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1474  (
    .A(\$abc$1320$n186 ),
    .B(a[1]),
    .Y(\$abc$1320$n187 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1475  (
    .A(\$abc$1320$n187 ),
    .B(b[1]),
    .Y(\$abc$1320$n188 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1476  (
    .A(\$abc$1320$n188 ),
    .B(\$abc$1320$n185 ),
    .Y(\$abc$1320$n189 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1477  (
    .A(\$abc$1320$n189 ),
    .B(\$abc$1320$n184 ),
    .Y(\$abc$1320$n190 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1478  (
    .A(\$abc$1320$n145 ),
    .B(\$abc$1320$n108_1 ),
    .Y(\$abc$1320$n191 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1479  (
    .A(\$abc$1320$n191 ),
    .B(\$abc$1320$n185 ),
    .Y(\$abc$1320$n192 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1480  (
    .A(\$abc$1320$n192 ),
    .B(b[1]),
    .Y(\$abc$1320$n193 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1481  (
    .A(\$abc$1320$n193 ),
    .B(\$abc$1320$n183 ),
    .Y(\$abc$1320$n194 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1482  (
    .A(\$abc$1320$n194 ),
    .B(\$abc$1320$n190 ),
    .Y(\$abc$1320$n195 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1483  (
    .A(\$abc$1320$n195 ),
    .B(a[1]),
    .Y(\$abc$1320$n196 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1484  (
    .A(\$abc$1320$n193 ),
    .B(\$abc$1320$n183 ),
    .Y(\$abc$1320$n197 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1485  (
    .A(\$abc$1320$n189 ),
    .B(\$abc$1320$n184 ),
    .Y(\$abc$1320$n198 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1486  (
    .A(\$abc$1320$n198 ),
    .B(\$abc$1320$n197 ),
    .Y(\$abc$1320$n199 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1487  (
    .A(\$abc$1320$n199 ),
    .B(\$abc$1320$n108_1 ),
    .Y(\$abc$1320$n200 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1488  (
    .A(\$abc$1320$n200 ),
    .B(\$abc$1320$n196 ),
    .Y(\$abc$1320$n201 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1489  (
    .A(\$abc$1320$n201 ),
    .B(\$abc$1320$n182 ),
    .Y(\$abc$1320$n202 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1490  (
    .A(\$abc$1320$n199 ),
    .B(\$abc$1320$n108_1 ),
    .Y(\$abc$1320$n203_1 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1491  (
    .A(\$abc$1320$n195 ),
    .B(a[1]),
    .Y(\$abc$1320$n204 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1492  (
    .A(\$abc$1320$n204 ),
    .B(\$abc$1320$n203_1 ),
    .Y(\$abc$1320$n205_1 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1493  (
    .A(\$abc$1320$n205_1 ),
    .B(\$abc$1320$n181 ),
    .Y(\$abc$1320$n206 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1494  (
    .A(\$abc$1320$n206 ),
    .B(\$abc$1320$n202 ),
    .Y(\$abc$1320$n207_1 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1495  (
    .A(\$abc$1320$n207_1 ),
    .B(b[2]),
    .Y(\$abc$1320$n208 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1496  (
    .A(\$abc$1320$n208 ),
    .Y(\$abc$1320$n209_1 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1497  (
    .A(\$abc$1320$n199 ),
    .B(b[2]),
    .Y(\$abc$1320$n210 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1498  (
    .A(\$abc$1320$n210 ),
    .B(\$abc$1320$n209_1 ),
    .Y(\$abc$1320$n211_1 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1499  (
    .A(\$abc$1320$n211_1 ),
    .B(\$abc$1320$n180 ),
    .Y(\$abc$1320$n212 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1500  (
    .A(\$abc$1320$n180 ),
    .Y(\$abc$1320$n213_1 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1501  (
    .A(\$abc$1320$n211_1 ),
    .Y(\$abc$1320$n214 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1502  (
    .A(\$abc$1320$n214 ),
    .B(\$abc$1320$n213_1 ),
    .Y(\$abc$1320$n215_1 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1503  (
    .A(\$abc$1320$n215_1 ),
    .B(\$abc$1320$n212 ),
    .Y(\$abc$1320$n216 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1504  (
    .A(\$abc$1320$n216 ),
    .B(\$abc$1320$n98 ),
    .Y(\$abc$1320$n217_1 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1505  (
    .A(\$abc$1320$n171 ),
    .B(\$abc$1320$n50 ),
    .Y(\$abc$1320$n218 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1506  (
    .A(\$abc$1320$n168 ),
    .B(\$abc$1320$n129_1 ),
    .Y(\$abc$1320$n219_1 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1507  (
    .A(\$abc$1320$n170 ),
    .B(\$abc$1320$n125 ),
    .Y(\$abc$1320$n220 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1508  (
    .A(\$abc$1320$n220 ),
    .B(\$abc$1320$n55 ),
    .Y(\$abc$1320$n221 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1509  (
    .A(\$abc$1320$n221 ),
    .B(\$abc$1320$n219_1 ),
    .Y(\$abc$1320$n222 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1510  (
    .A(\$abc$1320$n222 ),
    .B(\$abc$1320$n218 ),
    .Y(\$abc$1320$n223 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1511  (
    .A(\$abc$1320$n223 ),
    .B(\$abc$1320$n217_1 ),
    .Y(\$abc$1320$n224 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1512  (
    .A(\$abc$1320$n224 ),
    .B(\$abc$1320$n179 ),
    .Y(\$0\z[7:0] [3])
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1513  (
    .A(\$abc$1320$n61 ),
    .B(\$abc$1320$n73 ),
    .Y(\$abc$1320$n226 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1514  (
    .A(b[4]),
    .B(a[4]),
    .Y(\$abc$1320$n227 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1515  (
    .A(\$abc$1320$n227 ),
    .B(\$abc$1320$n226 ),
    .Y(\$abc$1320$n228 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1516  (
    .A(\$abc$1320$n228 ),
    .Y(\$abc$1320$n229 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1517  (
    .A(b[3]),
    .B(\$abc$1320$n169 ),
    .Y(\$abc$1320$n230 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1518  (
    .A(\$abc$1320$n230 ),
    .B(\$abc$1320$n177 ),
    .Y(\$abc$1320$n231 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1519  (
    .A(\$abc$1320$n231 ),
    .Y(\$abc$1320$n232 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1520  (
    .A(\$abc$1320$n232 ),
    .B(\$abc$1320$n229 ),
    .Y(\$abc$1320$n233 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1521  (
    .A(\$abc$1320$n231 ),
    .B(\$abc$1320$n228 ),
    .Y(\$abc$1320$n234 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1522  (
    .A(\$abc$1320$n234 ),
    .B(\$abc$1320$n233 ),
    .Y(\$abc$1320$n235 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1523  (
    .A(\$abc$1320$n235 ),
    .B(\$abc$1320$n55 ),
    .Y(\$abc$1320$n236 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1524  (
    .A(\$abc$1320$n61 ),
    .B(\$abc$1320$n35 ),
    .Y(\$abc$1320$n237 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1525  (
    .A(\$abc$1320$n211_1 ),
    .B(\$abc$1320$n35 ),
    .Y(\$abc$1320$n238 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1526  (
    .A(\$abc$1320$n238 ),
    .Y(\$abc$1320$n239 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1527  (
    .A(\$abc$1320$n202 ),
    .B(\$abc$1320$n203_1 ),
    .Y(\$abc$1320$n240 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1528  (
    .A(\$abc$1320$n145 ),
    .B(\$abc$1320$n80 ),
    .Y(\$abc$1320$n241 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1529  (
    .A(a[2]),
    .B(\$abc$1320$n35 ),
    .Y(\$abc$1320$n242 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1530  (
    .A(\$abc$1320$n242 ),
    .B(\$abc$1320$n109_1 ),
    .Y(\$abc$1320$n243 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1531  (
    .A(\$abc$1320$n243 ),
    .B(\$abc$1320$n183 ),
    .Y(\$abc$1320$n244 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1532  (
    .A(\$abc$1320$n244 ),
    .B(\$abc$1320$n241 ),
    .Y(\$abc$1320$n245 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1533  (
    .A(\$abc$1320$n183 ),
    .B(\$abc$1320$n73 ),
    .Y(\$abc$1320$n246 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1534  (
    .A(\$abc$1320$n246 ),
    .Y(\$abc$1320$n247 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1535  (
    .A(b[0]),
    .B(a[4]),
    .Y(\$abc$1320$n248 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1536  (
    .A(\$abc$1320$n248 ),
    .B(\$abc$1320$n169 ),
    .Y(\$abc$1320$n249 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1537  (
    .A(\$abc$1320$n249 ),
    .B(\$abc$1320$n247 ),
    .Y(\$abc$1320$n250 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1538  (
    .A(\$abc$1320$n250 ),
    .B(\$abc$1320$n245 ),
    .Y(\$abc$1320$n251 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1539  (
    .A(\$abc$1320$n241 ),
    .Y(\$abc$1320$n252 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1540  (
    .A(\$abc$1320$n137 ),
    .B(a[0]),
    .Y(\$abc$1320$n253 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1541  (
    .A(\$abc$1320$n253 ),
    .B(\$abc$1320$n112_1 ),
    .Y(\$abc$1320$n254 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1542  (
    .A(\$abc$1320$n254 ),
    .B(\$abc$1320$n184 ),
    .Y(\$abc$1320$n255 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1543  (
    .A(\$abc$1320$n255 ),
    .B(\$abc$1320$n252 ),
    .Y(\$abc$1320$n256 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1544  (
    .A(\$abc$1320$n249 ),
    .Y(\$abc$1320$n257 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1545  (
    .A(\$abc$1320$n257 ),
    .B(\$abc$1320$n246 ),
    .Y(\$abc$1320$n258 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1546  (
    .A(\$abc$1320$n258 ),
    .B(\$abc$1320$n256 ),
    .Y(\$abc$1320$n259 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1547  (
    .A(\$abc$1320$n259 ),
    .B(\$abc$1320$n251 ),
    .Y(\$abc$1320$n260 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1548  (
    .A(\$abc$1320$n260 ),
    .B(b[1]),
    .Y(\$abc$1320$n261 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1549  (
    .A(\$abc$1320$n248 ),
    .B(b[1]),
    .Y(\$abc$1320$n262 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1550  (
    .A(\$abc$1320$n262 ),
    .Y(\$abc$1320$n263 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1551  (
    .A(\$abc$1320$n263 ),
    .B(\$abc$1320$n261 ),
    .Y(\$abc$1320$n264 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1552  (
    .A(\$abc$1320$n264 ),
    .B(a[2]),
    .Y(\$abc$1320$n265 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1553  (
    .A(\$abc$1320$n258 ),
    .B(\$abc$1320$n256 ),
    .Y(\$abc$1320$n266 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1554  (
    .A(\$abc$1320$n250 ),
    .B(\$abc$1320$n245 ),
    .Y(\$abc$1320$n267 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1555  (
    .A(\$abc$1320$n267 ),
    .B(\$abc$1320$n266 ),
    .Y(\$abc$1320$n268 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1556  (
    .A(\$abc$1320$n268 ),
    .B(\$abc$1320$n65 ),
    .Y(\$abc$1320$n269 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1557  (
    .A(\$abc$1320$n262 ),
    .B(\$abc$1320$n269 ),
    .Y(\$abc$1320$n270 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1558  (
    .A(\$abc$1320$n270 ),
    .B(\$abc$1320$n137 ),
    .Y(\$abc$1320$n271 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1559  (
    .A(\$abc$1320$n271 ),
    .B(\$abc$1320$n265 ),
    .Y(\$abc$1320$n272 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1560  (
    .A(\$abc$1320$n272 ),
    .B(\$abc$1320$n240 ),
    .Y(\$abc$1320$n273 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1561  (
    .A(\$abc$1320$n205_1 ),
    .B(\$abc$1320$n181 ),
    .Y(\$abc$1320$n274 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1562  (
    .A(\$abc$1320$n274 ),
    .B(\$abc$1320$n196 ),
    .Y(\$abc$1320$n275 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1563  (
    .A(\$abc$1320$n270 ),
    .B(\$abc$1320$n137 ),
    .Y(\$abc$1320$n276 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1564  (
    .A(\$abc$1320$n264 ),
    .B(a[2]),
    .Y(\$abc$1320$n277 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1565  (
    .A(\$abc$1320$n277 ),
    .B(\$abc$1320$n276 ),
    .Y(\$abc$1320$n278 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1566  (
    .A(\$abc$1320$n278 ),
    .B(\$abc$1320$n275 ),
    .Y(\$abc$1320$n279 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1567  (
    .A(\$abc$1320$n279 ),
    .B(\$abc$1320$n273 ),
    .Y(\$abc$1320$n280 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1568  (
    .A(\$abc$1320$n280 ),
    .B(b[2]),
    .Y(\$abc$1320$n281 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1569  (
    .A(\$abc$1320$n270 ),
    .B(b[2]),
    .Y(\$abc$1320$n282 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1570  (
    .A(\$abc$1320$n282 ),
    .Y(\$abc$1320$n283 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1571  (
    .A(\$abc$1320$n283 ),
    .B(\$abc$1320$n281 ),
    .Y(\$abc$1320$n284 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1572  (
    .A(\$abc$1320$n284 ),
    .B(a[1]),
    .Y(\$abc$1320$n285 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1573  (
    .A(\$abc$1320$n278 ),
    .B(\$abc$1320$n275 ),
    .Y(\$abc$1320$n286 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1574  (
    .A(\$abc$1320$n272 ),
    .B(\$abc$1320$n240 ),
    .Y(\$abc$1320$n287 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1575  (
    .A(\$abc$1320$n287 ),
    .B(\$abc$1320$n286 ),
    .Y(\$abc$1320$n288 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1576  (
    .A(\$abc$1320$n288 ),
    .B(\$abc$1320$n67 ),
    .Y(\$abc$1320$n289 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1577  (
    .A(\$abc$1320$n282 ),
    .B(\$abc$1320$n289 ),
    .Y(\$abc$1320$n290 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1578  (
    .A(\$abc$1320$n290 ),
    .B(\$abc$1320$n108_1 ),
    .Y(\$abc$1320$n291 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1579  (
    .A(\$abc$1320$n291 ),
    .B(\$abc$1320$n285 ),
    .Y(\$abc$1320$n292 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1580  (
    .A(\$abc$1320$n292 ),
    .B(\$abc$1320$n239 ),
    .Y(\$abc$1320$n293 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1581  (
    .A(\$abc$1320$n290 ),
    .B(\$abc$1320$n108_1 ),
    .Y(\$abc$1320$n294 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1582  (
    .A(\$abc$1320$n284 ),
    .B(a[1]),
    .Y(\$abc$1320$n295 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1583  (
    .A(\$abc$1320$n295 ),
    .B(\$abc$1320$n294 ),
    .Y(\$abc$1320$n296 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1584  (
    .A(\$abc$1320$n296 ),
    .B(\$abc$1320$n238 ),
    .Y(\$abc$1320$n297 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1585  (
    .A(\$abc$1320$n297 ),
    .B(\$abc$1320$n293 ),
    .Y(\$abc$1320$n298 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1586  (
    .A(\$abc$1320$n298 ),
    .B(b[3]),
    .Y(\$abc$1320$n299 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1587  (
    .A(\$abc$1320$n299 ),
    .Y(\$abc$1320$n300 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1588  (
    .A(\$abc$1320$n290 ),
    .B(b[3]),
    .Y(\$abc$1320$n301 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1589  (
    .A(\$abc$1320$n301 ),
    .B(\$abc$1320$n300 ),
    .Y(\$abc$1320$n302 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1590  (
    .A(\$abc$1320$n302 ),
    .Y(\$abc$1320$n303 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1591  (
    .A(\$abc$1320$n303 ),
    .B(\$abc$1320$n237 ),
    .Y(\$abc$1320$n304 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1592  (
    .A(\$abc$1320$n303 ),
    .B(\$abc$1320$n237 ),
    .Y(\$abc$1320$n305 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1593  (
    .A(\$abc$1320$n305 ),
    .B(\$abc$1320$n98 ),
    .Y(\$abc$1320$n306 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1594  (
    .A(\$abc$1320$n306 ),
    .B(\$abc$1320$n304 ),
    .Y(\$abc$1320$n307 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1595  (
    .A(\$abc$1320$n227 ),
    .B(\$abc$1320$n129_1 ),
    .Y(\$abc$1320$n308 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1596  (
    .A(\$abc$1320$n228 ),
    .B(\$abc$1320$n50 ),
    .Y(\$abc$1320$n309 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1597  (
    .A(\$abc$1320$n226 ),
    .B(\$abc$1320$n125 ),
    .Y(\$abc$1320$n310 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1598  (
    .A(\$abc$1320$n310 ),
    .B(\$abc$1320$n309 ),
    .Y(\$abc$1320$n311 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1599  (
    .A(\$abc$1320$n311 ),
    .B(\$abc$1320$n308 ),
    .Y(\$abc$1320$n312 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1600  (
    .A(\$abc$1320$n312 ),
    .B(\$abc$1320$n307 ),
    .Y(\$abc$1320$n313 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1601  (
    .A(\$abc$1320$n313 ),
    .B(\$abc$1320$n54 ),
    .Y(\$abc$1320$n314 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1602  (
    .A(\$abc$1320$n314 ),
    .B(\$abc$1320$n236 ),
    .Y(\$0\z[7:0] [4])
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1603  (
    .A(\$abc$1320$n58 ),
    .B(\$abc$1320$n74 ),
    .Y(\$abc$1320$n316 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1604  (
    .A(b[5]),
    .B(a[5]),
    .Y(\$abc$1320$n317 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1605  (
    .A(\$abc$1320$n317 ),
    .B(\$abc$1320$n316 ),
    .Y(\$abc$1320$n318 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1606  (
    .A(\$abc$1320$n318 ),
    .Y(\$abc$1320$n319 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1607  (
    .A(b[4]),
    .B(\$abc$1320$n73 ),
    .Y(\$abc$1320$n320 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1608  (
    .A(\$abc$1320$n320 ),
    .B(\$abc$1320$n234 ),
    .Y(\$abc$1320$n321 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1609  (
    .A(\$abc$1320$n321 ),
    .Y(\$abc$1320$n322 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1610  (
    .A(\$abc$1320$n322 ),
    .B(\$abc$1320$n319 ),
    .Y(\$abc$1320$n323 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1611  (
    .A(\$abc$1320$n321 ),
    .B(\$abc$1320$n318 ),
    .Y(\$abc$1320$n324 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1612  (
    .A(\$abc$1320$n324 ),
    .B(\$abc$1320$n323 ),
    .Y(\$abc$1320$n325 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1613  (
    .A(\$abc$1320$n325 ),
    .B(\$abc$1320$n55 ),
    .Y(\$abc$1320$n326 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1614  (
    .A(\$abc$1320$n58 ),
    .B(\$abc$1320$n35 ),
    .Y(\$abc$1320$n327 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1615  (
    .A(\$abc$1320$n302 ),
    .B(\$abc$1320$n35 ),
    .Y(\$abc$1320$n328 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1616  (
    .A(\$abc$1320$n328 ),
    .Y(\$abc$1320$n329 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1617  (
    .A(\$abc$1320$n36 ),
    .B(\$abc$1320$n74 ),
    .Y(\$abc$1320$n330 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1618  (
    .A(\$abc$1320$n330 ),
    .Y(\$abc$1320$n331 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1619  (
    .A(\$abc$1320$n331 ),
    .B(b[1]),
    .Y(\$abc$1320$n332 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1620  (
    .A(\$abc$1320$n266 ),
    .B(\$abc$1320$n247 ),
    .Y(\$abc$1320$n333 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1621  (
    .A(\$abc$1320$n330 ),
    .B(a[4]),
    .Y(\$abc$1320$n334 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1622  (
    .A(\$abc$1320$n248 ),
    .B(\$abc$1320$n74 ),
    .Y(\$abc$1320$n335 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1623  (
    .A(\$abc$1320$n335 ),
    .B(\$abc$1320$n334 ),
    .Y(\$abc$1320$n336 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1624  (
    .A(\$abc$1320$n336 ),
    .Y(\$abc$1320$n337 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1625  (
    .A(\$abc$1320$n337 ),
    .B(\$abc$1320$n333 ),
    .Y(\$abc$1320$n338 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1626  (
    .A(\$abc$1320$n251 ),
    .B(\$abc$1320$n246 ),
    .Y(\$abc$1320$n339 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1627  (
    .A(\$abc$1320$n336 ),
    .B(\$abc$1320$n339 ),
    .Y(\$abc$1320$n340 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1628  (
    .A(\$abc$1320$n340 ),
    .B(\$abc$1320$n338 ),
    .Y(\$abc$1320$n341 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1629  (
    .A(\$abc$1320$n341 ),
    .B(\$abc$1320$n65 ),
    .Y(\$abc$1320$n342 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1630  (
    .A(\$abc$1320$n342 ),
    .B(\$abc$1320$n332 ),
    .Y(\$abc$1320$n343 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1631  (
    .A(\$abc$1320$n343 ),
    .B(b[2]),
    .Y(\$abc$1320$n344 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1632  (
    .A(\$abc$1320$n286 ),
    .B(\$abc$1320$n265 ),
    .Y(\$abc$1320$n345 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1633  (
    .A(\$abc$1320$n332 ),
    .Y(\$abc$1320$n346 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1634  (
    .A(\$abc$1320$n336 ),
    .B(\$abc$1320$n339 ),
    .Y(\$abc$1320$n347 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1635  (
    .A(\$abc$1320$n337 ),
    .B(\$abc$1320$n333 ),
    .Y(\$abc$1320$n348 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1636  (
    .A(\$abc$1320$n348 ),
    .B(\$abc$1320$n347 ),
    .Y(\$abc$1320$n349 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1637  (
    .A(\$abc$1320$n349 ),
    .B(b[1]),
    .Y(\$abc$1320$n350 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1638  (
    .A(\$abc$1320$n350 ),
    .B(\$abc$1320$n346 ),
    .Y(\$abc$1320$n351 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1639  (
    .A(\$abc$1320$n351 ),
    .B(a[3]),
    .Y(\$abc$1320$n352 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1640  (
    .A(\$abc$1320$n343 ),
    .B(\$abc$1320$n169 ),
    .Y(\$abc$1320$n353 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1641  (
    .A(\$abc$1320$n353 ),
    .B(\$abc$1320$n352 ),
    .Y(\$abc$1320$n354 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1642  (
    .A(\$abc$1320$n354 ),
    .B(\$abc$1320$n345 ),
    .Y(\$abc$1320$n355 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1643  (
    .A(\$abc$1320$n273 ),
    .B(\$abc$1320$n276 ),
    .Y(\$abc$1320$n356 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1644  (
    .A(\$abc$1320$n343 ),
    .B(\$abc$1320$n169 ),
    .Y(\$abc$1320$n357 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1645  (
    .A(\$abc$1320$n351 ),
    .B(a[3]),
    .Y(\$abc$1320$n358 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1646  (
    .A(\$abc$1320$n358 ),
    .B(\$abc$1320$n357 ),
    .Y(\$abc$1320$n359 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1647  (
    .A(\$abc$1320$n359 ),
    .B(\$abc$1320$n356 ),
    .Y(\$abc$1320$n360 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1648  (
    .A(\$abc$1320$n360 ),
    .B(\$abc$1320$n355 ),
    .Y(\$abc$1320$n361 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1649  (
    .A(\$abc$1320$n361 ),
    .B(\$abc$1320$n67 ),
    .Y(\$abc$1320$n362 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1650  (
    .A(\$abc$1320$n362 ),
    .B(\$abc$1320$n344 ),
    .Y(\$abc$1320$n363 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1651  (
    .A(\$abc$1320$n363 ),
    .B(b[3]),
    .Y(\$abc$1320$n364 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1652  (
    .A(\$abc$1320$n364 ),
    .Y(\$abc$1320$n365 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1653  (
    .A(\$abc$1320$n293 ),
    .B(\$abc$1320$n294 ),
    .Y(\$abc$1320$n366 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1654  (
    .A(\$abc$1320$n363 ),
    .B(\$abc$1320$n137 ),
    .Y(\$abc$1320$n367 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1655  (
    .A(\$abc$1320$n344 ),
    .Y(\$abc$1320$n368 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1656  (
    .A(\$abc$1320$n359 ),
    .B(\$abc$1320$n356 ),
    .Y(\$abc$1320$n369 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1657  (
    .A(\$abc$1320$n354 ),
    .B(\$abc$1320$n345 ),
    .Y(\$abc$1320$n370 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1658  (
    .A(\$abc$1320$n370 ),
    .B(\$abc$1320$n369 ),
    .Y(\$abc$1320$n371 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1659  (
    .A(\$abc$1320$n371 ),
    .B(b[2]),
    .Y(\$abc$1320$n372 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1660  (
    .A(\$abc$1320$n372 ),
    .B(\$abc$1320$n368 ),
    .Y(\$abc$1320$n373 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1661  (
    .A(\$abc$1320$n373 ),
    .B(a[2]),
    .Y(\$abc$1320$n374 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1662  (
    .A(\$abc$1320$n374 ),
    .B(\$abc$1320$n367 ),
    .Y(\$abc$1320$n375 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1663  (
    .A(\$abc$1320$n375 ),
    .B(\$abc$1320$n366 ),
    .Y(\$abc$1320$n376 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1664  (
    .A(\$abc$1320$n296 ),
    .B(\$abc$1320$n238 ),
    .Y(\$abc$1320$n377 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1665  (
    .A(\$abc$1320$n377 ),
    .B(\$abc$1320$n285 ),
    .Y(\$abc$1320$n378 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1666  (
    .A(\$abc$1320$n373 ),
    .B(a[2]),
    .Y(\$abc$1320$n379 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1667  (
    .A(\$abc$1320$n363 ),
    .B(\$abc$1320$n137 ),
    .Y(\$abc$1320$n380 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1668  (
    .A(\$abc$1320$n380 ),
    .B(\$abc$1320$n379 ),
    .Y(\$abc$1320$n381 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1669  (
    .A(\$abc$1320$n381 ),
    .B(\$abc$1320$n378 ),
    .Y(\$abc$1320$n382 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1670  (
    .A(\$abc$1320$n382 ),
    .B(\$abc$1320$n376 ),
    .Y(\$abc$1320$n383 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1671  (
    .A(\$abc$1320$n383 ),
    .B(b[3]),
    .Y(\$abc$1320$n384 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1672  (
    .A(\$abc$1320$n384 ),
    .B(\$abc$1320$n365 ),
    .Y(\$abc$1320$n385 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1673  (
    .A(\$abc$1320$n385 ),
    .B(a[1]),
    .Y(\$abc$1320$n386 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1674  (
    .A(\$abc$1320$n381 ),
    .B(\$abc$1320$n378 ),
    .Y(\$abc$1320$n387 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1675  (
    .A(\$abc$1320$n375 ),
    .B(\$abc$1320$n366 ),
    .Y(\$abc$1320$n388 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1676  (
    .A(\$abc$1320$n388 ),
    .B(\$abc$1320$n387 ),
    .Y(\$abc$1320$n389 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1677  (
    .A(\$abc$1320$n389 ),
    .B(\$abc$1320$n68 ),
    .Y(\$abc$1320$n390 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1678  (
    .A(\$abc$1320$n390 ),
    .B(\$abc$1320$n364 ),
    .Y(\$abc$1320$n391 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1679  (
    .A(\$abc$1320$n391 ),
    .B(\$abc$1320$n108_1 ),
    .Y(\$abc$1320$n392 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1680  (
    .A(\$abc$1320$n392 ),
    .B(\$abc$1320$n386 ),
    .Y(\$abc$1320$n393 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1681  (
    .A(\$abc$1320$n393 ),
    .B(\$abc$1320$n329 ),
    .Y(\$abc$1320$n394 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1682  (
    .A(\$abc$1320$n391 ),
    .B(\$abc$1320$n108_1 ),
    .Y(\$abc$1320$n395 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1683  (
    .A(\$abc$1320$n385 ),
    .B(a[1]),
    .Y(\$abc$1320$n396 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1684  (
    .A(\$abc$1320$n396 ),
    .B(\$abc$1320$n395 ),
    .Y(\$abc$1320$n397 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1685  (
    .A(\$abc$1320$n397 ),
    .B(\$abc$1320$n328 ),
    .Y(\$abc$1320$n398 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1686  (
    .A(\$abc$1320$n398 ),
    .B(\$abc$1320$n394 ),
    .Y(\$abc$1320$n399 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1687  (
    .A(\$abc$1320$n399 ),
    .B(\$abc$1320$n61 ),
    .Y(\$abc$1320$n400 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1688  (
    .A(\$abc$1320$n391 ),
    .B(b[4]),
    .Y(\$abc$1320$n401 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1689  (
    .A(\$abc$1320$n401 ),
    .B(\$abc$1320$n400 ),
    .Y(\$abc$1320$n402 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1690  (
    .A(\$abc$1320$n402 ),
    .Y(\$abc$1320$n403 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1691  (
    .A(\$abc$1320$n403 ),
    .B(\$abc$1320$n327 ),
    .Y(\$abc$1320$n404 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1692  (
    .A(\$abc$1320$n403 ),
    .B(\$abc$1320$n327 ),
    .Y(\$abc$1320$n405 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1693  (
    .A(\$abc$1320$n405 ),
    .B(\$abc$1320$n98 ),
    .Y(\$abc$1320$n406 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1694  (
    .A(\$abc$1320$n406 ),
    .B(\$abc$1320$n404 ),
    .Y(\$abc$1320$n407 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1695  (
    .A(\$abc$1320$n317 ),
    .B(\$abc$1320$n129_1 ),
    .Y(\$abc$1320$n408 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1696  (
    .A(\$abc$1320$n318 ),
    .B(\$abc$1320$n50 ),
    .Y(\$abc$1320$n409 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1697  (
    .A(\$abc$1320$n316 ),
    .B(\$abc$1320$n125 ),
    .Y(\$abc$1320$n410 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1698  (
    .A(\$abc$1320$n410 ),
    .B(\$abc$1320$n409 ),
    .Y(\$abc$1320$n411 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1699  (
    .A(\$abc$1320$n411 ),
    .B(\$abc$1320$n408 ),
    .Y(\$abc$1320$n412 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1700  (
    .A(\$abc$1320$n412 ),
    .B(\$abc$1320$n407 ),
    .Y(\$abc$1320$n413 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1701  (
    .A(\$abc$1320$n413 ),
    .B(\$abc$1320$n54 ),
    .Y(\$abc$1320$n414 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1702  (
    .A(\$abc$1320$n414 ),
    .B(\$abc$1320$n326 ),
    .Y(\$0\z[7:0] [5])
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1703  (
    .A(\$abc$1320$n59 ),
    .B(\$abc$1320$n76 ),
    .Y(\$abc$1320$n416 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1704  (
    .A(b[6]),
    .B(a[6]),
    .Y(\$abc$1320$n417 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1705  (
    .A(\$abc$1320$n417 ),
    .B(\$abc$1320$n416 ),
    .Y(\$abc$1320$n418 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1706  (
    .A(\$abc$1320$n418 ),
    .Y(\$abc$1320$n419 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1707  (
    .A(b[5]),
    .B(\$abc$1320$n74 ),
    .Y(\$abc$1320$n420 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1708  (
    .A(\$abc$1320$n420 ),
    .B(\$abc$1320$n324 ),
    .Y(\$abc$1320$n421 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1709  (
    .A(\$abc$1320$n421 ),
    .Y(\$abc$1320$n422 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1710  (
    .A(\$abc$1320$n422 ),
    .B(\$abc$1320$n419 ),
    .Y(\$abc$1320$n423 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1711  (
    .A(\$abc$1320$n421 ),
    .B(\$abc$1320$n418 ),
    .Y(\$abc$1320$n424 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1712  (
    .A(\$abc$1320$n424 ),
    .B(\$abc$1320$n423 ),
    .Y(\$abc$1320$n425 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1713  (
    .A(\$abc$1320$n425 ),
    .B(\$abc$1320$n55 ),
    .Y(\$abc$1320$n426 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1714  (
    .A(\$abc$1320$n59 ),
    .B(\$abc$1320$n35 ),
    .Y(\$abc$1320$n427 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1715  (
    .A(\$abc$1320$n402 ),
    .B(\$abc$1320$n35 ),
    .Y(\$abc$1320$n428 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1716  (
    .A(\$abc$1320$n428 ),
    .Y(\$abc$1320$n429 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1717  (
    .A(\$abc$1320$n393 ),
    .B(\$abc$1320$n329 ),
    .Y(\$abc$1320$n430 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1718  (
    .A(\$abc$1320$n430 ),
    .B(\$abc$1320$n395 ),
    .Y(\$abc$1320$n431 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1719  (
    .A(\$abc$1320$n36 ),
    .B(\$abc$1320$n76 ),
    .Y(\$abc$1320$n432 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1720  (
    .A(\$abc$1320$n432 ),
    .Y(\$abc$1320$n433 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1721  (
    .A(\$abc$1320$n433 ),
    .B(b[1]),
    .Y(\$abc$1320$n434 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1722  (
    .A(\$abc$1320$n434 ),
    .Y(\$abc$1320$n435 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1723  (
    .A(\$abc$1320$n334 ),
    .B(\$abc$1320$n339 ),
    .Y(\$abc$1320$n436 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1724  (
    .A(\$abc$1320$n436 ),
    .B(\$abc$1320$n335 ),
    .Y(\$abc$1320$n437 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1725  (
    .A(\$abc$1320$n432 ),
    .B(\$abc$1320$n74 ),
    .Y(\$abc$1320$n438 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1726  (
    .A(\$abc$1320$n432 ),
    .B(\$abc$1320$n74 ),
    .Y(\$abc$1320$n439 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1727  (
    .A(\$abc$1320$n439 ),
    .Y(\$abc$1320$n440 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1728  (
    .A(\$abc$1320$n440 ),
    .B(\$abc$1320$n438 ),
    .Y(\$abc$1320$n441 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1729  (
    .A(\$abc$1320$n441 ),
    .B(\$abc$1320$n437 ),
    .Y(\$abc$1320$n442 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1730  (
    .A(\$abc$1320$n335 ),
    .Y(\$abc$1320$n443 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1731  (
    .A(\$abc$1320$n334 ),
    .Y(\$abc$1320$n444 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1732  (
    .A(\$abc$1320$n444 ),
    .B(\$abc$1320$n333 ),
    .Y(\$abc$1320$n445 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1733  (
    .A(\$abc$1320$n445 ),
    .B(\$abc$1320$n443 ),
    .Y(\$abc$1320$n446 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1734  (
    .A(\$abc$1320$n441 ),
    .Y(\$abc$1320$n447 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1735  (
    .A(\$abc$1320$n447 ),
    .B(\$abc$1320$n446 ),
    .Y(\$abc$1320$n448 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1736  (
    .A(\$abc$1320$n448 ),
    .B(\$abc$1320$n442 ),
    .Y(\$abc$1320$n449 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1737  (
    .A(\$abc$1320$n449 ),
    .B(b[1]),
    .Y(\$abc$1320$n450 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1738  (
    .A(\$abc$1320$n450 ),
    .B(\$abc$1320$n435 ),
    .Y(\$abc$1320$n451 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1739  (
    .A(\$abc$1320$n451 ),
    .B(a[4]),
    .Y(\$abc$1320$n452 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1740  (
    .A(\$abc$1320$n447 ),
    .B(\$abc$1320$n446 ),
    .Y(\$abc$1320$n453 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1741  (
    .A(\$abc$1320$n441 ),
    .B(\$abc$1320$n437 ),
    .Y(\$abc$1320$n454 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1742  (
    .A(\$abc$1320$n454 ),
    .B(\$abc$1320$n453 ),
    .Y(\$abc$1320$n455 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1743  (
    .A(\$abc$1320$n455 ),
    .B(\$abc$1320$n65 ),
    .Y(\$abc$1320$n456 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1744  (
    .A(\$abc$1320$n456 ),
    .B(\$abc$1320$n434 ),
    .Y(\$abc$1320$n457 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1745  (
    .A(\$abc$1320$n457 ),
    .B(\$abc$1320$n73 ),
    .Y(\$abc$1320$n458 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1746  (
    .A(\$abc$1320$n458 ),
    .B(\$abc$1320$n452 ),
    .Y(\$abc$1320$n459 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1747  (
    .A(\$abc$1320$n358 ),
    .B(\$abc$1320$n356 ),
    .Y(\$abc$1320$n460 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1748  (
    .A(\$abc$1320$n460 ),
    .B(\$abc$1320$n357 ),
    .Y(\$abc$1320$n461 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1749  (
    .A(\$abc$1320$n461 ),
    .B(\$abc$1320$n459 ),
    .Y(\$abc$1320$n462 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1750  (
    .A(\$abc$1320$n457 ),
    .B(\$abc$1320$n73 ),
    .Y(\$abc$1320$n463 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1751  (
    .A(\$abc$1320$n451 ),
    .B(a[4]),
    .Y(\$abc$1320$n464 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1752  (
    .A(\$abc$1320$n464 ),
    .B(\$abc$1320$n463 ),
    .Y(\$abc$1320$n465 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1753  (
    .A(\$abc$1320$n353 ),
    .B(\$abc$1320$n345 ),
    .Y(\$abc$1320$n466 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1754  (
    .A(\$abc$1320$n466 ),
    .B(\$abc$1320$n352 ),
    .Y(\$abc$1320$n467 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1755  (
    .A(\$abc$1320$n467 ),
    .B(\$abc$1320$n465 ),
    .Y(\$abc$1320$n468 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1756  (
    .A(\$abc$1320$n468 ),
    .B(\$abc$1320$n462 ),
    .Y(\$abc$1320$n469 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1757  (
    .A(\$abc$1320$n469 ),
    .B(b[2]),
    .Y(\$abc$1320$n470 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1758  (
    .A(\$abc$1320$n457 ),
    .B(b[2]),
    .Y(\$abc$1320$n471 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1759  (
    .A(\$abc$1320$n471 ),
    .Y(\$abc$1320$n472 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1760  (
    .A(\$abc$1320$n472 ),
    .B(\$abc$1320$n470 ),
    .Y(\$abc$1320$n473 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1761  (
    .A(\$abc$1320$n473 ),
    .B(a[3]),
    .Y(\$abc$1320$n474 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1762  (
    .A(\$abc$1320$n461 ),
    .B(\$abc$1320$n459 ),
    .Y(\$abc$1320$n475 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1763  (
    .A(\$abc$1320$n475 ),
    .B(b[2]),
    .Y(\$abc$1320$n476 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1764  (
    .A(\$abc$1320$n476 ),
    .B(\$abc$1320$n462 ),
    .Y(\$abc$1320$n477 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1765  (
    .A(\$abc$1320$n471 ),
    .B(\$abc$1320$n477 ),
    .Y(\$abc$1320$n478 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1766  (
    .A(\$abc$1320$n478 ),
    .B(\$abc$1320$n169 ),
    .Y(\$abc$1320$n479 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1767  (
    .A(\$abc$1320$n479 ),
    .B(\$abc$1320$n474 ),
    .Y(\$abc$1320$n480 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1768  (
    .A(\$abc$1320$n374 ),
    .B(\$abc$1320$n366 ),
    .Y(\$abc$1320$n481 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1769  (
    .A(\$abc$1320$n481 ),
    .B(\$abc$1320$n367 ),
    .Y(\$abc$1320$n482 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1770  (
    .A(\$abc$1320$n482 ),
    .B(\$abc$1320$n480 ),
    .Y(\$abc$1320$n483 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1771  (
    .A(\$abc$1320$n478 ),
    .B(\$abc$1320$n169 ),
    .Y(\$abc$1320$n484 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1772  (
    .A(\$abc$1320$n473 ),
    .B(a[3]),
    .Y(\$abc$1320$n485 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1773  (
    .A(\$abc$1320$n485 ),
    .B(\$abc$1320$n484 ),
    .Y(\$abc$1320$n486 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1774  (
    .A(\$abc$1320$n380 ),
    .B(\$abc$1320$n378 ),
    .Y(\$abc$1320$n487 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1775  (
    .A(\$abc$1320$n487 ),
    .B(\$abc$1320$n379 ),
    .Y(\$abc$1320$n488 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1776  (
    .A(\$abc$1320$n488 ),
    .B(\$abc$1320$n486 ),
    .Y(\$abc$1320$n489 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1777  (
    .A(\$abc$1320$n489 ),
    .B(\$abc$1320$n483 ),
    .Y(\$abc$1320$n490 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1778  (
    .A(\$abc$1320$n490 ),
    .B(b[3]),
    .Y(\$abc$1320$n491 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1779  (
    .A(\$abc$1320$n478 ),
    .B(b[3]),
    .Y(\$abc$1320$n492 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1780  (
    .A(\$abc$1320$n492 ),
    .Y(\$abc$1320$n493 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1781  (
    .A(\$abc$1320$n493 ),
    .B(\$abc$1320$n491 ),
    .Y(\$abc$1320$n494 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1782  (
    .A(\$abc$1320$n494 ),
    .B(a[2]),
    .Y(\$abc$1320$n495 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1783  (
    .A(\$abc$1320$n482 ),
    .B(\$abc$1320$n480 ),
    .Y(\$abc$1320$n496 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1784  (
    .A(\$abc$1320$n496 ),
    .B(b[3]),
    .Y(\$abc$1320$n497 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1785  (
    .A(\$abc$1320$n497 ),
    .B(\$abc$1320$n483 ),
    .Y(\$abc$1320$n498 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1786  (
    .A(\$abc$1320$n492 ),
    .B(\$abc$1320$n498 ),
    .Y(\$abc$1320$n499 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1787  (
    .A(\$abc$1320$n499 ),
    .B(\$abc$1320$n137 ),
    .Y(\$abc$1320$n500 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1788  (
    .A(\$abc$1320$n500 ),
    .B(\$abc$1320$n495 ),
    .Y(\$abc$1320$n501 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1789  (
    .A(\$abc$1320$n501 ),
    .B(\$abc$1320$n431 ),
    .Y(\$abc$1320$n502 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1790  (
    .A(\$abc$1320$n398 ),
    .B(\$abc$1320$n386 ),
    .Y(\$abc$1320$n503 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1791  (
    .A(\$abc$1320$n499 ),
    .B(\$abc$1320$n137 ),
    .Y(\$abc$1320$n504 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1792  (
    .A(\$abc$1320$n494 ),
    .B(a[2]),
    .Y(\$abc$1320$n505 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1793  (
    .A(\$abc$1320$n505 ),
    .B(\$abc$1320$n504 ),
    .Y(\$abc$1320$n506 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1794  (
    .A(\$abc$1320$n506 ),
    .B(\$abc$1320$n503 ),
    .Y(\$abc$1320$n507 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1795  (
    .A(\$abc$1320$n507 ),
    .B(\$abc$1320$n502 ),
    .Y(\$abc$1320$n508 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1796  (
    .A(\$abc$1320$n508 ),
    .B(b[4]),
    .Y(\$abc$1320$n509 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1797  (
    .A(\$abc$1320$n499 ),
    .B(b[4]),
    .Y(\$abc$1320$n510 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1798  (
    .A(\$abc$1320$n510 ),
    .Y(\$abc$1320$n511 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1799  (
    .A(\$abc$1320$n511 ),
    .B(\$abc$1320$n509 ),
    .Y(\$abc$1320$n512 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1800  (
    .A(\$abc$1320$n512 ),
    .B(a[1]),
    .Y(\$abc$1320$n513 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1801  (
    .A(\$abc$1320$n501 ),
    .B(\$abc$1320$n431 ),
    .Y(\$abc$1320$n514 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1802  (
    .A(\$abc$1320$n514 ),
    .B(b[4]),
    .Y(\$abc$1320$n515 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1803  (
    .A(\$abc$1320$n515 ),
    .B(\$abc$1320$n502 ),
    .Y(\$abc$1320$n516 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1804  (
    .A(\$abc$1320$n510 ),
    .B(\$abc$1320$n516 ),
    .Y(\$abc$1320$n517 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1805  (
    .A(\$abc$1320$n517 ),
    .B(\$abc$1320$n108_1 ),
    .Y(\$abc$1320$n518 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1806  (
    .A(\$abc$1320$n518 ),
    .B(\$abc$1320$n513 ),
    .Y(\$abc$1320$n519 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1807  (
    .A(\$abc$1320$n519 ),
    .B(\$abc$1320$n429 ),
    .Y(\$abc$1320$n520 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1808  (
    .A(\$abc$1320$n519 ),
    .B(\$abc$1320$n429 ),
    .Y(\$abc$1320$n521 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1809  (
    .A(\$abc$1320$n521 ),
    .B(\$abc$1320$n58 ),
    .Y(\$abc$1320$n522 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1810  (
    .A(\$abc$1320$n522 ),
    .B(\$abc$1320$n520 ),
    .Y(\$abc$1320$n523 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1811  (
    .A(\$abc$1320$n512 ),
    .B(\$abc$1320$n58 ),
    .Y(\$abc$1320$n524 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1812  (
    .A(\$abc$1320$n524 ),
    .B(\$abc$1320$n523 ),
    .Y(\$abc$1320$n525 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1813  (
    .A(\$abc$1320$n525 ),
    .Y(\$abc$1320$n526 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1814  (
    .A(\$abc$1320$n526 ),
    .B(\$abc$1320$n427 ),
    .Y(\$abc$1320$n527 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1815  (
    .A(\$abc$1320$n427 ),
    .Y(\$abc$1320$n528 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1816  (
    .A(\$abc$1320$n525 ),
    .B(\$abc$1320$n528 ),
    .Y(\$abc$1320$n529 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1817  (
    .A(\$abc$1320$n529 ),
    .B(\$abc$1320$n527 ),
    .Y(\$abc$1320$n530 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1818  (
    .A(\$abc$1320$n530 ),
    .B(\$abc$1320$n98 ),
    .Y(\$abc$1320$n531 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1819  (
    .A(\$abc$1320$n418 ),
    .B(\$abc$1320$n50 ),
    .Y(\$abc$1320$n532 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1820  (
    .A(\$abc$1320$n416 ),
    .B(\$abc$1320$n125 ),
    .Y(\$abc$1320$n533 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1821  (
    .A(\$abc$1320$n417 ),
    .Y(\$abc$1320$n534 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1822  (
    .A(\$abc$1320$n534 ),
    .B(\$abc$1320$n130_1 ),
    .Y(\$abc$1320$n535 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1823  (
    .A(\$abc$1320$n535 ),
    .B(\$abc$1320$n533 ),
    .Y(\$abc$1320$n536 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1824  (
    .A(\$abc$1320$n536 ),
    .B(\$abc$1320$n54 ),
    .Y(\$abc$1320$n537 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1825  (
    .A(\$abc$1320$n537 ),
    .B(\$abc$1320$n532 ),
    .Y(\$abc$1320$n538 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1826  (
    .A(\$abc$1320$n538 ),
    .B(\$abc$1320$n531 ),
    .Y(\$abc$1320$n539 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1827  (
    .A(\$abc$1320$n539 ),
    .B(\$abc$1320$n426 ),
    .Y(\$0\z[7:0] [6])
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1828  (
    .A(\$abc$1320$n525 ),
    .B(a[0]),
    .Y(\$abc$1320$n541 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1829  (
    .A(\$abc$1320$n541 ),
    .B(\$abc$1320$n108_1 ),
    .Y(\$abc$1320$n542 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1830  (
    .A(\$abc$1320$n541 ),
    .B(\$abc$1320$n108_1 ),
    .Y(\$abc$1320$n543 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1831  (
    .A(\$abc$1320$n543 ),
    .B(b[6]),
    .Y(\$abc$1320$n544 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1832  (
    .A(\$abc$1320$n544 ),
    .B(\$abc$1320$n542 ),
    .Y(\$abc$1320$n545 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1833  (
    .A(\$abc$1320$n483 ),
    .B(\$abc$1320$n484 ),
    .Y(\$abc$1320$n546 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1834  (
    .A(\$abc$1320$n546 ),
    .B(\$abc$1320$n73 ),
    .Y(\$abc$1320$n547 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1835  (
    .A(\$abc$1320$n546 ),
    .B(\$abc$1320$n73 ),
    .Y(\$abc$1320$n548 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1836  (
    .A(\$abc$1320$n548 ),
    .B(b[3]),
    .Y(\$abc$1320$n549 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1837  (
    .A(\$abc$1320$n549 ),
    .B(\$abc$1320$n547 ),
    .Y(\$abc$1320$n550 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1838  (
    .A(\$abc$1320$n550 ),
    .Y(\$abc$1320$n551 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1839  (
    .A(\$abc$1320$n62 ),
    .B(\$abc$1320$n35 ),
    .Y(\$abc$1320$n552 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1840  (
    .A(\$abc$1320$n462 ),
    .B(\$abc$1320$n463 ),
    .Y(\$abc$1320$n553 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1841  (
    .A(\$abc$1320$n553 ),
    .Y(\$abc$1320$n554 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1842  (
    .A(\$abc$1320$n554 ),
    .B(a[5]),
    .Y(\$abc$1320$n555 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1843  (
    .A(\$abc$1320$n553 ),
    .B(\$abc$1320$n74 ),
    .Y(\$abc$1320$n556 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1844  (
    .A(\$abc$1320$n556 ),
    .B(\$abc$1320$n67 ),
    .Y(\$abc$1320$n557 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1845  (
    .A(\$abc$1320$n557 ),
    .Y(\$abc$1320$n558 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1846  (
    .A(\$abc$1320$n558 ),
    .B(\$abc$1320$n555 ),
    .Y(\$abc$1320$n559 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1847  (
    .A(\$abc$1320$n36 ),
    .B(\$abc$1320$n77 ),
    .Y(\$abc$1320$n560 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1848  (
    .A(\$abc$1320$n560 ),
    .Y(\$abc$1320$n561 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1849  (
    .A(\$abc$1320$n453 ),
    .B(a[6]),
    .Y(\$abc$1320$n562 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1850  (
    .A(\$abc$1320$n330 ),
    .B(\$abc$1320$n76 ),
    .Y(\$abc$1320$n563 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1851  (
    .A(\$abc$1320$n563 ),
    .Y(\$abc$1320$n564 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1852  (
    .A(\$abc$1320$n564 ),
    .B(\$abc$1320$n442 ),
    .Y(\$abc$1320$n565 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1853  (
    .A(\$abc$1320$n565 ),
    .B(\$abc$1320$n562 ),
    .Y(\$abc$1320$n566 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1854  (
    .A(\$abc$1320$n566 ),
    .B(\$abc$1320$n65 ),
    .Y(\$abc$1320$n567 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1855  (
    .A(\$abc$1320$n567 ),
    .B(\$abc$1320$n561 ),
    .Y(\$abc$1320$n568 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1856  (
    .A(\$abc$1320$n567 ),
    .B(\$abc$1320$n561 ),
    .Y(\$abc$1320$n569 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1857  (
    .A(\$abc$1320$n569 ),
    .Y(\$abc$1320$n570 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1858  (
    .A(\$abc$1320$n570 ),
    .B(\$abc$1320$n568 ),
    .Y(\$abc$1320$n571 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1859  (
    .A(\$abc$1320$n571 ),
    .B(\$abc$1320$n559 ),
    .Y(\$abc$1320$n572 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1860  (
    .A(\$abc$1320$n571 ),
    .B(\$abc$1320$n559 ),
    .Y(\$abc$1320$n573 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1861  (
    .A(\$abc$1320$n573 ),
    .Y(\$abc$1320$n574 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1862  (
    .A(\$abc$1320$n574 ),
    .B(\$abc$1320$n572 ),
    .Y(\$abc$1320$n575 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1863  (
    .A(\$abc$1320$n575 ),
    .Y(\$abc$1320$n576 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1864  (
    .A(\$abc$1320$n576 ),
    .B(\$abc$1320$n552 ),
    .Y(\$abc$1320$n577 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1865  (
    .A(\$abc$1320$n577 ),
    .Y(\$abc$1320$n578 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1866  (
    .A(\$abc$1320$n576 ),
    .B(\$abc$1320$n552 ),
    .Y(\$abc$1320$n579 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1867  (
    .A(\$abc$1320$n579 ),
    .B(\$abc$1320$n578 ),
    .Y(\$abc$1320$n580 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1868  (
    .A(\$abc$1320$n580 ),
    .Y(\$abc$1320$n581 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1869  (
    .A(\$abc$1320$n581 ),
    .B(\$abc$1320$n551 ),
    .Y(\$abc$1320$n582 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1870  (
    .A(\$abc$1320$n580 ),
    .B(\$abc$1320$n550 ),
    .Y(\$abc$1320$n583 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1871  (
    .A(\$abc$1320$n583 ),
    .B(\$abc$1320$n582 ),
    .Y(\$abc$1320$n584 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1872  (
    .A(\$abc$1320$n584 ),
    .Y(\$abc$1320$n585 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1873  (
    .A(\$abc$1320$n502 ),
    .B(\$abc$1320$n504 ),
    .Y(\$abc$1320$n586 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1874  (
    .A(\$abc$1320$n586 ),
    .Y(\$abc$1320$n587 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1875  (
    .A(\$abc$1320$n587 ),
    .B(a[3]),
    .Y(\$abc$1320$n588 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1876  (
    .A(\$abc$1320$n586 ),
    .B(\$abc$1320$n169 ),
    .Y(\$abc$1320$n589 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1877  (
    .A(\$abc$1320$n589 ),
    .B(\$abc$1320$n61 ),
    .Y(\$abc$1320$n590 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1878  (
    .A(\$abc$1320$n590 ),
    .Y(\$abc$1320$n591 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1879  (
    .A(\$abc$1320$n591 ),
    .B(\$abc$1320$n588 ),
    .Y(\$abc$1320$n592 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1880  (
    .A(\$abc$1320$n592 ),
    .B(\$abc$1320$n585 ),
    .Y(\$abc$1320$n593 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1881  (
    .A(\$abc$1320$n592 ),
    .B(\$abc$1320$n585 ),
    .Y(\$abc$1320$n594 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1882  (
    .A(\$abc$1320$n594 ),
    .Y(\$abc$1320$n595 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1883  (
    .A(\$abc$1320$n595 ),
    .B(\$abc$1320$n593 ),
    .Y(\$abc$1320$n596 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1884  (
    .A(\$abc$1320$n596 ),
    .Y(\$abc$1320$n597 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1885  (
    .A(\$abc$1320$n513 ),
    .Y(\$abc$1320$n598 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1886  (
    .A(\$abc$1320$n521 ),
    .B(\$abc$1320$n598 ),
    .Y(\$abc$1320$n599 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1887  (
    .A(\$abc$1320$n599 ),
    .B(\$abc$1320$n137 ),
    .Y(\$abc$1320$n600 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1888  (
    .A(\$abc$1320$n599 ),
    .B(\$abc$1320$n137 ),
    .Y(\$abc$1320$n601 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1889  (
    .A(\$abc$1320$n601 ),
    .B(\$abc$1320$n58 ),
    .Y(\$abc$1320$n602 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1890  (
    .A(\$abc$1320$n602 ),
    .B(\$abc$1320$n600 ),
    .Y(\$abc$1320$n603 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1891  (
    .A(\$abc$1320$n603 ),
    .B(\$abc$1320$n597 ),
    .Y(\$abc$1320$n604 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1892  (
    .A(\$abc$1320$n600 ),
    .B(b[5]),
    .Y(\$abc$1320$n605 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1893  (
    .A(\$abc$1320$n605 ),
    .B(\$abc$1320$n601 ),
    .Y(\$abc$1320$n606 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1894  (
    .A(\$abc$1320$n606 ),
    .B(\$abc$1320$n596 ),
    .Y(\$abc$1320$n607 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1895  (
    .A(\$abc$1320$n607 ),
    .B(\$abc$1320$n604 ),
    .Y(\$abc$1320$n608 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1896  (
    .A(\$abc$1320$n608 ),
    .B(\$abc$1320$n545 ),
    .Y(\$abc$1320$n609 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1897  (
    .A(\$abc$1320$n608 ),
    .B(\$abc$1320$n545 ),
    .Y(\$abc$1320$n610 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1898  (
    .A(\$abc$1320$n610 ),
    .B(\$abc$1320$n98 ),
    .Y(\$abc$1320$n611 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1899  (
    .A(\$abc$1320$n611 ),
    .B(\$abc$1320$n609 ),
    .Y(\$abc$1320$n612 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1900  (
    .A(\$abc$1320$n62 ),
    .B(\$abc$1320$n77 ),
    .Y(\$abc$1320$n613 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1901  (
    .A(b[7]),
    .B(a[7]),
    .Y(\$abc$1320$n614 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1902  (
    .A(\$abc$1320$n614 ),
    .B(\$abc$1320$n613 ),
    .Y(\$abc$1320$n615 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1903  (
    .A(b[6]),
    .B(\$abc$1320$n76 ),
    .Y(\$abc$1320$n616 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1904  (
    .A(\$abc$1320$n616 ),
    .B(\$abc$1320$n424 ),
    .Y(\$abc$1320$n617 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1905  (
    .A(\$abc$1320$n617 ),
    .B(\$abc$1320$n615 ),
    .Y(\$abc$1320$n618 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1906  (
    .A(\$abc$1320$n617 ),
    .B(\$abc$1320$n615 ),
    .Y(\$abc$1320$n619 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1907  (
    .A(\$abc$1320$n619 ),
    .B(\$abc$1320$n54 ),
    .Y(\$abc$1320$n620 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1908  (
    .A(\$abc$1320$n620 ),
    .B(\$abc$1320$n618 ),
    .Y(\$abc$1320$n621 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1909  (
    .A(\$abc$1320$n615 ),
    .B(\$abc$1320$n50 ),
    .Y(\$abc$1320$n622 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1910  (
    .A(\$abc$1320$n125 ),
    .Y(\$abc$1320$n623 )
  );
  NOT \$abc$1320$auto$blifparse.cc:286:parse_blif$1911  (
    .A(\$abc$1320$n613 ),
    .Y(\$abc$1320$n624 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1912  (
    .A(\$abc$1320$n624 ),
    .B(\$abc$1320$n623 ),
    .Y(\$abc$1320$n625 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1913  (
    .A(\$abc$1320$n614 ),
    .B(\$abc$1320$n129_1 ),
    .Y(\$abc$1320$n626 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1914  (
    .A(\$abc$1320$n626 ),
    .B(\$abc$1320$n625 ),
    .Y(\$abc$1320$n627 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1915  (
    .A(\$abc$1320$n627 ),
    .B(\$abc$1320$n622 ),
    .Y(\$abc$1320$n628 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1916  (
    .A(\$abc$1320$n628 ),
    .B(\$abc$1320$n621 ),
    .Y(\$abc$1320$n629 )
  );
  NAND \$abc$1320$auto$blifparse.cc:286:parse_blif$1917  (
    .A(\$abc$1320$n629 ),
    .B(\$abc$1320$n612 ),
    .Y(\$0\z[7:0] [7])
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1918  (
    .A(\$abc$1320$n124_1 ),
    .B(opc[2]),
    .Y(\$abc$1320$n631 )
  );
  NOR \$abc$1320$auto$blifparse.cc:286:parse_blif$1919  (
    .A(\$abc$1320$n631 ),
    .B(\$abc$1320$n45 ),
    .Y(\$abc$1320$n219 )
  );
  \$_DLATCH_P_  \$auto$simplemap.cc:517:simplemap_dlatch$574  (
    .D(\$0\z[7:0] [0]),
    .E(\$abc$1320$n219 ),
    .Q(z[0])
  );
  \$_DLATCH_P_  \$auto$simplemap.cc:517:simplemap_dlatch$575  (
    .D(\$0\z[7:0] [1]),
    .E(\$abc$1320$n219 ),
    .Q(z[1])
  );
  \$_DLATCH_P_  \$auto$simplemap.cc:517:simplemap_dlatch$576  (
    .D(\$0\z[7:0] [2]),
    .E(\$abc$1320$n219 ),
    .Q(z[2])
  );
  \$_DLATCH_P_  \$auto$simplemap.cc:517:simplemap_dlatch$577  (
    .D(\$0\z[7:0] [3]),
    .E(\$abc$1320$n219 ),
    .Q(z[3])
  );
  \$_DLATCH_P_  \$auto$simplemap.cc:517:simplemap_dlatch$578  (
    .D(\$0\z[7:0] [4]),
    .E(\$abc$1320$n219 ),
    .Q(z[4])
  );
  \$_DLATCH_P_  \$auto$simplemap.cc:517:simplemap_dlatch$579  (
    .D(\$0\z[7:0] [5]),
    .E(\$abc$1320$n219 ),
    .Q(z[5])
  );
  \$_DLATCH_P_  \$auto$simplemap.cc:517:simplemap_dlatch$580  (
    .D(\$0\z[7:0] [6]),
    .E(\$abc$1320$n219 ),
    .Q(z[6])
  );
  \$_DLATCH_P_  \$auto$simplemap.cc:517:simplemap_dlatch$581  (
    .D(\$0\z[7:0] [7]),
    .E(\$abc$1320$n219 ),
    .Q(z[7])
  );
endmodule
